///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Goibibo_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Bus element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("5665a9ed-be37-4238-aa99-053318db9133")]
    public partial class Bus : RepoGenBaseFolder
    {
        static Bus instance = new Bus();
        BusFolders.BusTicketBookingOnlineBookACVolvoAppFolder _busticketbookingonlinebookacvolvo;
        BusFolders.StateBankOfIndiaInternetBankingAppFolder _statebankofindiainternetbanking;

        /// <summary>
        /// Gets the singleton class instance representing the Bus element repository.
        /// </summary>
        [RepositoryFolder("5665a9ed-be37-4238-aa99-053318db9133")]
        public static Bus Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Bus() 
            : base("Bus", "/", null, 0, false, "5665a9ed-be37-4238-aa99-053318db9133", ".\\RepositoryImages\\Bus5665a9ed.rximgres")
        {
            _busticketbookingonlinebookacvolvo = new BusFolders.BusTicketBookingOnlineBookACVolvoAppFolder(this);
            _statebankofindiainternetbanking = new BusFolders.StateBankOfIndiaInternetBankingAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5665a9ed-be37-4238-aa99-053318db9133")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The BusTicketBookingOnlineBookACVolvo folder.
        /// </summary>
        [RepositoryFolder("34b455a0-12b1-4c45-9b80-8befabba6397")]
        public virtual BusFolders.BusTicketBookingOnlineBookACVolvoAppFolder BusTicketBookingOnlineBookACVolvo
        {
            get { return _busticketbookingonlinebookacvolvo; }
        }

        /// <summary>
        /// The StateBankOfIndiaInternetBanking folder.
        /// </summary>
        [RepositoryFolder("b5cd388e-6e44-43a0-beb7-32cff957b964")]
        public virtual BusFolders.StateBankOfIndiaInternetBankingAppFolder StateBankOfIndiaInternetBanking
        {
            get { return _statebankofindiainternetbanking; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class BusFolders
    {
        /// <summary>
        /// The BusTicketBookingOnlineBookACVolvoAppFolder folder.
        /// </summary>
        [RepositoryFolder("34b455a0-12b1-4c45-9b80-8befabba6397")]
        public partial class BusTicketBookingOnlineBookACVolvoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iconbusdbblueico24lh12padt5padb5Info;
            RepoItemInfo _gisourceInfo;
            RepoItemInfo _maintxtInfo;
            RepoItemInfo _gidestinationInfo;
            RepoItemInfo _currentInfo;
            RepoItemInfo _gionwardtextInfo;
            RepoItemInfo _spantag22Info;
            RepoItemInfo _gisearchbtnInfo;
            RepoItemInfo _timeInfo;
            RepoItemInfo _boardingpointInfo;
            RepoItemInfo _droppingpointInfo;
            RepoItemInfo _busoperatorsInfo;
            RepoItemInfo _atagcpInfo;
            RepoItemInfo _ftbookbtnInfo;
            RepoItemInfo _onwredbusnewat200001192974000153034Info;
            RepoItemInfo _bponwredbusnewat2000011929740001530Info;
            RepoItemInfo _confirmInfo;
            RepoItemInfo _cancellationpolicyInfo;
            RepoItemInfo _javascriptvoid0Info;
            RepoItemInfo _adultchoose1Info;
            RepoItemInfo _adultfirstname1Info;
            RepoItemInfo _emailInfo;
            RepoItemInfo _mobileInfo;
            RepoItemInfo _spantagfarebreakupInfo;
            RepoItemInfo _javascriptvoid01Info;
            RepoItemInfo _firstbusInfo;
            RepoItemInfo _get10percentuptors50offInfo;
            RepoItemInfo _makepaymentInfo;
            RepoItemInfo _iconinfodibico14greydrmarginl10vmiInfo;
            RepoItemInfo _netbankingInfo;
            RepoItemInfo _paynetbrbInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _httpsgoibiboibcdncomstyleguideimaInfo;

            /// <summary>
            /// Creates a new BusTicketBookingOnlineBookACVolvo  folder.
            /// </summary>
            public BusTicketBookingOnlineBookACVolvoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BusTicketBookingOnlineBookACVolvo", "/dom[@domain='www.goibibo.com']", parentFolder, 30000, null, false, "34b455a0-12b1-4c45-9b80-8befabba6397", "")
            {
                _iconbusdbblueico24lh12padt5padb5Info = new RepoItemInfo(this, "IconBusDbBlueIco24Lh12PadT5PadB5", "body/div[1]/div[1]/ul/li[4]/?/?/i", 30000, null, "bd607d5a-14f3-45c2-bb98-251a067b8dbd");
                _gisourceInfo = new RepoItemInfo(this, "GiSource", ".//input[#'gi_source']", 30000, null, "6b662d6f-e218-4f5e-a4d1-929e6b159455");
                _maintxtInfo = new RepoItemInfo(this, "MainTxt", ".//div[#'gi_source_wrapper']/?/?/ul/li[1]/div[1]/div", 30000, null, "27d2edf0-e889-4fd8-bbdb-33faca285b15");
                _gidestinationInfo = new RepoItemInfo(this, "GiDestination", ".//input[#'gi_destination']", 30000, null, "773a27cd-44b2-4241-8013-e7a8c2b22b78");
                _currentInfo = new RepoItemInfo(this, "Current", ".//div[#'gi_destination_wrapper']/?/?/ul/li[1]", 30000, null, "cf76471f-3e25-45fb-821b-6bca40d72e80");
                _gionwardtextInfo = new RepoItemInfo(this, "GiOnwardText", ".//input[#'gi_onward_text']", 30000, null, "e1cca4c2-e2dc-4602-b2a9-ffc293e4f963");
                _spantag22Info = new RepoItemInfo(this, "SpanTag22", ".//td[#'jrdp_start-calen_1_22_2019']/?/?/span[@innertext='22']", 30000, null, "ba14c234-4e6e-4166-b134-2fe83649de6a");
                _gisearchbtnInfo = new RepoItemInfo(this, "GiSearchBtn", ".//button[#'gi_search_btn']", 30000, null, "f2b50ad8-fcda-417e-bf28-3048d6db296e");
                _timeInfo = new RepoItemInfo(this, "Time", ".//a[#'timesliner']/?/?/span[@innertext='Time']", 30000, null, "00187e9a-a18d-4c1e-b496-667c5c57d3c7");
                _boardingpointInfo = new RepoItemInfo(this, "BoardingPoint", ".//a[#'bpliner']/?/?/span[@innertext='Boarding Point']", 30000, null, "820cd36e-da69-455d-ae6c-9557eaa4f169");
                _droppingpointInfo = new RepoItemInfo(this, "DroppingPoint", ".//a[#'dpliner']/?/?/span[@innertext='Dropping Point ']", 30000, null, "a2c64a6a-850f-48a7-bc53-6fbd96e65892");
                _busoperatorsInfo = new RepoItemInfo(this, "BusOperators", ".//a[#'opliner']/?/?/span[@innertext='Bus Operators']", 30000, null, "2ccc74db-54f1-435c-ba5f-58a161bc35a7");
                _atagcpInfo = new RepoItemInfo(this, "ATagCp", ".//a[#'cp']", 30000, null, "04d67ec1-4090-40a6-a04c-043566e11796");
                _ftbookbtnInfo = new RepoItemInfo(this, "FtBookbtn", ".//ul[#'fl']/li/div[4]/div/div[2]/?/?/a[@id='ft_bookbtn']", 30000, null, "fbe03390-719d-4924-bd57-4708231db827");
                _onwredbusnewat200001192974000153034Info = new RepoItemInfo(this, "OnwRedbusnewAt200001192974000153034", ".//a[#'onw~redbusnew@2000011929740001530~34']", 30000, null, "c72a8b88-e22e-4163-9746-9f023279e131");
                _bponwredbusnewat2000011929740001530Info = new RepoItemInfo(this, "BpOnwRedbusnewAt2000011929740001530", ".//select[#'bp-onw-redbusnew@2000011929740001530']", 30000, null, "ad1cf446-1f9d-46a8-8ec8-2b61521f71b8");
                _confirmInfo = new RepoItemInfo(this, "Confirm", ".//a[#'confirm']", 30000, null, "4eb348f7-77ac-4761-8dee-47bf99ce2092");
                _cancellationpolicyInfo = new RepoItemInfo(this, "CancellationPolicy", ".//div[#'bk_step1']/div[2]/div[2]/div[2]/div[3]/a[@innertext='Cancellation Policy']", 30000, null, "ee892efc-d60f-4d4a-947b-59f4265d13c4");
                _javascriptvoid0Info = new RepoItemInfo(this, "JavascriptVoid0", ".//div[#'go_fareRulespopUp']/?/?/a[@href='javascript:void(0)']", 30000, null, "44d0f48c-0fb6-4d57-88dc-1bed0cc75cf6");
                _adultchoose1Info = new RepoItemInfo(this, "Adultchoose1", ".//select[#'adultchoose1']", 30000, null, "4af44aaa-19ad-46bf-b5bb-79a74a57a90d");
                _adultfirstname1Info = new RepoItemInfo(this, "Adultfirstname1", ".//input[#'adultfirstname1']", 30000, null, "17b77e8c-7fbe-4d99-9014-778f2bee0ff0");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "84f41f63-ae93-4875-8b7b-e60bb2e10f69");
                _mobileInfo = new RepoItemInfo(this, "Mobile", ".//input[#'mobile']", 30000, null, "0e90fd48-894c-48cf-995d-b90ebb9d1250");
                _spantagfarebreakupInfo = new RepoItemInfo(this, "SpanTagFareBreakup", ".//a[#'link_fb']/span[@innertext=' Fare Breakup']", 30000, null, "d6d73c7d-9fb0-4037-b4e2-742d3010e510");
                _javascriptvoid01Info = new RepoItemInfo(this, "JavascriptVoid01", ".//div[#'go_fb_popCont']/?/?/a[@href='javascript:void(0)']", 30000, null, "607973f1-4476-4b82-9ae9-7c5c8e9257ef");
                _firstbusInfo = new RepoItemInfo(this, "FIRSTBUS", ".//input[#'FIRSTBUS']", 30000, null, "b1194cfc-ea48-4954-8a1c-22e09d9fdc18");
                _get10percentuptors50offInfo = new RepoItemInfo(this, "Get10PercentUptoRs50Off", ".//div[#'bk_step1']/div[2]/div[2]/div[8]/div[1]/label[2]/span[@innertext='Get 10% upto Rs. 50 off']", 30000, null, "a423863f-b9af-4e21-8852-a65da9fc415f");
                _makepaymentInfo = new RepoItemInfo(this, "MakePayment", ".//input[#'makePayment']", 30000, null, "f9f8df40-3a12-4088-b5f3-130bf220b913");
                _iconinfodibico14greydrmarginl10vmiInfo = new RepoItemInfo(this, "IconInfoDibIco14GreyDrMarginL10VMi", ".//div[#'pay_amount_section_cc_card']//a[@href~'^https://www\\.goibibo\\.com/b']/i", 30000, null, "dc53b6b3-296c-45e8-95b5-0bafeb095b83");
                _netbankingInfo = new RepoItemInfo(this, "NetBanking", ".//ul[#'tabnav_opts']/?/?/a[@innertext='Net Banking']", 30000, null, "09bb02be-10e6-45c4-8189-69e6f29d7f2a");
                _paynetbrbInfo = new RepoItemInfo(this, "PayNetbRb", ".//div[#'netBank']/div[2]/div[6]/?/?/input[@name='pay_netb_rb']", 30000, null, "4c22968c-5703-4149-abcd-38ae27d3ca48");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'netBank']/div[3]/div[4]/?/?/input[@type='submit']", 30000, null, "6a69210b-0de2-4e39-8217-0f00d692a320");
                _httpsgoibiboibcdncomstyleguideimaInfo = new RepoItemInfo(this, "HttpsGoibiboIbcdnComStyleguideIma", "body/div[1]/?/?/a[@href='https://www.goibibo.com/']/img[@src='https://goibibo.ibcdn.com/styleguide/images/goLogo.png']", 30000, null, "6b173318-99d8-48c5-a3d2-24c2bb0b58b1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("34b455a0-12b1-4c45-9b80-8befabba6397")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("34b455a0-12b1-4c45-9b80-8befabba6397")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IconBusDbBlueIco24Lh12PadT5PadB5 item.
            /// </summary>
            [RepositoryItem("bd607d5a-14f3-45c2-bb98-251a067b8dbd")]
            public virtual Ranorex.ITag IconBusDbBlueIco24Lh12PadT5PadB5
            {
                get
                {
                    return _iconbusdbblueico24lh12padt5padb5Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IconBusDbBlueIco24Lh12PadT5PadB5 item info.
            /// </summary>
            [RepositoryItemInfo("bd607d5a-14f3-45c2-bb98-251a067b8dbd")]
            public virtual RepoItemInfo IconBusDbBlueIco24Lh12PadT5PadB5Info
            {
                get
                {
                    return _iconbusdbblueico24lh12padt5padb5Info;
                }
            }

            /// <summary>
            /// The GiSource item.
            /// </summary>
            [RepositoryItem("6b662d6f-e218-4f5e-a4d1-929e6b159455")]
            public virtual Ranorex.InputTag GiSource
            {
                get
                {
                    return _gisourceInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GiSource item info.
            /// </summary>
            [RepositoryItemInfo("6b662d6f-e218-4f5e-a4d1-929e6b159455")]
            public virtual RepoItemInfo GiSourceInfo
            {
                get
                {
                    return _gisourceInfo;
                }
            }

            /// <summary>
            /// The MainTxt item.
            /// </summary>
            [RepositoryItem("27d2edf0-e889-4fd8-bbdb-33faca285b15")]
            public virtual Ranorex.DivTag MainTxt
            {
                get
                {
                    return _maintxtInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MainTxt item info.
            /// </summary>
            [RepositoryItemInfo("27d2edf0-e889-4fd8-bbdb-33faca285b15")]
            public virtual RepoItemInfo MainTxtInfo
            {
                get
                {
                    return _maintxtInfo;
                }
            }

            /// <summary>
            /// The GiDestination item.
            /// </summary>
            [RepositoryItem("773a27cd-44b2-4241-8013-e7a8c2b22b78")]
            public virtual Ranorex.InputTag GiDestination
            {
                get
                {
                    return _gidestinationInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GiDestination item info.
            /// </summary>
            [RepositoryItemInfo("773a27cd-44b2-4241-8013-e7a8c2b22b78")]
            public virtual RepoItemInfo GiDestinationInfo
            {
                get
                {
                    return _gidestinationInfo;
                }
            }

            /// <summary>
            /// The Current item.
            /// </summary>
            [RepositoryItem("cf76471f-3e25-45fb-821b-6bca40d72e80")]
            public virtual Ranorex.LiTag Current
            {
                get
                {
                    return _currentInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Current item info.
            /// </summary>
            [RepositoryItemInfo("cf76471f-3e25-45fb-821b-6bca40d72e80")]
            public virtual RepoItemInfo CurrentInfo
            {
                get
                {
                    return _currentInfo;
                }
            }

            /// <summary>
            /// The GiOnwardText item.
            /// </summary>
            [RepositoryItem("e1cca4c2-e2dc-4602-b2a9-ffc293e4f963")]
            public virtual Ranorex.InputTag GiOnwardText
            {
                get
                {
                    return _gionwardtextInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GiOnwardText item info.
            /// </summary>
            [RepositoryItemInfo("e1cca4c2-e2dc-4602-b2a9-ffc293e4f963")]
            public virtual RepoItemInfo GiOnwardTextInfo
            {
                get
                {
                    return _gionwardtextInfo;
                }
            }

            /// <summary>
            /// The SpanTag22 item.
            /// </summary>
            [RepositoryItem("ba14c234-4e6e-4166-b134-2fe83649de6a")]
            public virtual Ranorex.SpanTag SpanTag22
            {
                get
                {
                    return _spantag22Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag22 item info.
            /// </summary>
            [RepositoryItemInfo("ba14c234-4e6e-4166-b134-2fe83649de6a")]
            public virtual RepoItemInfo SpanTag22Info
            {
                get
                {
                    return _spantag22Info;
                }
            }

            /// <summary>
            /// The GiSearchBtn item.
            /// </summary>
            [RepositoryItem("f2b50ad8-fcda-417e-bf28-3048d6db296e")]
            public virtual Ranorex.ButtonTag GiSearchBtn
            {
                get
                {
                    return _gisearchbtnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The GiSearchBtn item info.
            /// </summary>
            [RepositoryItemInfo("f2b50ad8-fcda-417e-bf28-3048d6db296e")]
            public virtual RepoItemInfo GiSearchBtnInfo
            {
                get
                {
                    return _gisearchbtnInfo;
                }
            }

            /// <summary>
            /// The Time item.
            /// </summary>
            [RepositoryItem("00187e9a-a18d-4c1e-b496-667c5c57d3c7")]
            public virtual Ranorex.SpanTag Time
            {
                get
                {
                    return _timeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Time item info.
            /// </summary>
            [RepositoryItemInfo("00187e9a-a18d-4c1e-b496-667c5c57d3c7")]
            public virtual RepoItemInfo TimeInfo
            {
                get
                {
                    return _timeInfo;
                }
            }

            /// <summary>
            /// The BoardingPoint item.
            /// </summary>
            [RepositoryItem("820cd36e-da69-455d-ae6c-9557eaa4f169")]
            public virtual Ranorex.SpanTag BoardingPoint
            {
                get
                {
                    return _boardingpointInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BoardingPoint item info.
            /// </summary>
            [RepositoryItemInfo("820cd36e-da69-455d-ae6c-9557eaa4f169")]
            public virtual RepoItemInfo BoardingPointInfo
            {
                get
                {
                    return _boardingpointInfo;
                }
            }

            /// <summary>
            /// The DroppingPoint item.
            /// </summary>
            [RepositoryItem("a2c64a6a-850f-48a7-bc53-6fbd96e65892")]
            public virtual Ranorex.SpanTag DroppingPoint
            {
                get
                {
                    return _droppingpointInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The DroppingPoint item info.
            /// </summary>
            [RepositoryItemInfo("a2c64a6a-850f-48a7-bc53-6fbd96e65892")]
            public virtual RepoItemInfo DroppingPointInfo
            {
                get
                {
                    return _droppingpointInfo;
                }
            }

            /// <summary>
            /// The BusOperators item.
            /// </summary>
            [RepositoryItem("2ccc74db-54f1-435c-ba5f-58a161bc35a7")]
            public virtual Ranorex.SpanTag BusOperators
            {
                get
                {
                    return _busoperatorsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BusOperators item info.
            /// </summary>
            [RepositoryItemInfo("2ccc74db-54f1-435c-ba5f-58a161bc35a7")]
            public virtual RepoItemInfo BusOperatorsInfo
            {
                get
                {
                    return _busoperatorsInfo;
                }
            }

            /// <summary>
            /// The ATagCp item.
            /// </summary>
            [RepositoryItem("04d67ec1-4090-40a6-a04c-043566e11796")]
            public virtual Ranorex.ATag ATagCp
            {
                get
                {
                    return _atagcpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagCp item info.
            /// </summary>
            [RepositoryItemInfo("04d67ec1-4090-40a6-a04c-043566e11796")]
            public virtual RepoItemInfo ATagCpInfo
            {
                get
                {
                    return _atagcpInfo;
                }
            }

            /// <summary>
            /// The FtBookbtn item.
            /// </summary>
            [RepositoryItem("fbe03390-719d-4924-bd57-4708231db827")]
            public virtual Ranorex.ATag FtBookbtn
            {
                get
                {
                    return _ftbookbtnInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FtBookbtn item info.
            /// </summary>
            [RepositoryItemInfo("fbe03390-719d-4924-bd57-4708231db827")]
            public virtual RepoItemInfo FtBookbtnInfo
            {
                get
                {
                    return _ftbookbtnInfo;
                }
            }

            /// <summary>
            /// The OnwRedbusnewAt200001192974000153034 item.
            /// </summary>
            [RepositoryItem("c72a8b88-e22e-4163-9746-9f023279e131")]
            public virtual Ranorex.ATag OnwRedbusnewAt200001192974000153034
            {
                get
                {
                    return _onwredbusnewat200001192974000153034Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OnwRedbusnewAt200001192974000153034 item info.
            /// </summary>
            [RepositoryItemInfo("c72a8b88-e22e-4163-9746-9f023279e131")]
            public virtual RepoItemInfo OnwRedbusnewAt200001192974000153034Info
            {
                get
                {
                    return _onwredbusnewat200001192974000153034Info;
                }
            }

            /// <summary>
            /// The BpOnwRedbusnewAt2000011929740001530 item.
            /// </summary>
            [RepositoryItem("ad1cf446-1f9d-46a8-8ec8-2b61521f71b8")]
            public virtual Ranorex.SelectTag BpOnwRedbusnewAt2000011929740001530
            {
                get
                {
                    return _bponwredbusnewat2000011929740001530Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The BpOnwRedbusnewAt2000011929740001530 item info.
            /// </summary>
            [RepositoryItemInfo("ad1cf446-1f9d-46a8-8ec8-2b61521f71b8")]
            public virtual RepoItemInfo BpOnwRedbusnewAt2000011929740001530Info
            {
                get
                {
                    return _bponwredbusnewat2000011929740001530Info;
                }
            }

            /// <summary>
            /// The Confirm item.
            /// </summary>
            [RepositoryItem("4eb348f7-77ac-4761-8dee-47bf99ce2092")]
            public virtual Ranorex.ATag Confirm
            {
                get
                {
                    return _confirmInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Confirm item info.
            /// </summary>
            [RepositoryItemInfo("4eb348f7-77ac-4761-8dee-47bf99ce2092")]
            public virtual RepoItemInfo ConfirmInfo
            {
                get
                {
                    return _confirmInfo;
                }
            }

            /// <summary>
            /// The CancellationPolicy item.
            /// </summary>
            [RepositoryItem("ee892efc-d60f-4d4a-947b-59f4265d13c4")]
            public virtual Ranorex.ATag CancellationPolicy
            {
                get
                {
                    return _cancellationpolicyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CancellationPolicy item info.
            /// </summary>
            [RepositoryItemInfo("ee892efc-d60f-4d4a-947b-59f4265d13c4")]
            public virtual RepoItemInfo CancellationPolicyInfo
            {
                get
                {
                    return _cancellationpolicyInfo;
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item.
            /// </summary>
            [RepositoryItem("44d0f48c-0fb6-4d57-88dc-1bed0cc75cf6")]
            public virtual Ranorex.ATag JavascriptVoid0
            {
                get
                {
                    return _javascriptvoid0Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item info.
            /// </summary>
            [RepositoryItemInfo("44d0f48c-0fb6-4d57-88dc-1bed0cc75cf6")]
            public virtual RepoItemInfo JavascriptVoid0Info
            {
                get
                {
                    return _javascriptvoid0Info;
                }
            }

            /// <summary>
            /// The Adultchoose1 item.
            /// </summary>
            [RepositoryItem("4af44aaa-19ad-46bf-b5bb-79a74a57a90d")]
            public virtual Ranorex.SelectTag Adultchoose1
            {
                get
                {
                    return _adultchoose1Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Adultchoose1 item info.
            /// </summary>
            [RepositoryItemInfo("4af44aaa-19ad-46bf-b5bb-79a74a57a90d")]
            public virtual RepoItemInfo Adultchoose1Info
            {
                get
                {
                    return _adultchoose1Info;
                }
            }

            /// <summary>
            /// The Adultfirstname1 item.
            /// </summary>
            [RepositoryItem("17b77e8c-7fbe-4d99-9014-778f2bee0ff0")]
            public virtual Ranorex.InputTag Adultfirstname1
            {
                get
                {
                    return _adultfirstname1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Adultfirstname1 item info.
            /// </summary>
            [RepositoryItemInfo("17b77e8c-7fbe-4d99-9014-778f2bee0ff0")]
            public virtual RepoItemInfo Adultfirstname1Info
            {
                get
                {
                    return _adultfirstname1Info;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("84f41f63-ae93-4875-8b7b-e60bb2e10f69")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("84f41f63-ae93-4875-8b7b-e60bb2e10f69")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Mobile item.
            /// </summary>
            [RepositoryItem("0e90fd48-894c-48cf-995d-b90ebb9d1250")]
            public virtual Ranorex.InputTag Mobile
            {
                get
                {
                    return _mobileInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Mobile item info.
            /// </summary>
            [RepositoryItemInfo("0e90fd48-894c-48cf-995d-b90ebb9d1250")]
            public virtual RepoItemInfo MobileInfo
            {
                get
                {
                    return _mobileInfo;
                }
            }

            /// <summary>
            /// The SpanTagFareBreakup item.
            /// </summary>
            [RepositoryItem("d6d73c7d-9fb0-4037-b4e2-742d3010e510")]
            public virtual Ranorex.SpanTag SpanTagFareBreakup
            {
                get
                {
                    return _spantagfarebreakupInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagFareBreakup item info.
            /// </summary>
            [RepositoryItemInfo("d6d73c7d-9fb0-4037-b4e2-742d3010e510")]
            public virtual RepoItemInfo SpanTagFareBreakupInfo
            {
                get
                {
                    return _spantagfarebreakupInfo;
                }
            }

            /// <summary>
            /// The JavascriptVoid01 item.
            /// </summary>
            [RepositoryItem("607973f1-4476-4b82-9ae9-7c5c8e9257ef")]
            public virtual Ranorex.ATag JavascriptVoid01
            {
                get
                {
                    return _javascriptvoid01Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The JavascriptVoid01 item info.
            /// </summary>
            [RepositoryItemInfo("607973f1-4476-4b82-9ae9-7c5c8e9257ef")]
            public virtual RepoItemInfo JavascriptVoid01Info
            {
                get
                {
                    return _javascriptvoid01Info;
                }
            }

            /// <summary>
            /// The FIRSTBUS item.
            /// </summary>
            [RepositoryItem("b1194cfc-ea48-4954-8a1c-22e09d9fdc18")]
            public virtual Ranorex.InputTag FIRSTBUS
            {
                get
                {
                    return _firstbusInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FIRSTBUS item info.
            /// </summary>
            [RepositoryItemInfo("b1194cfc-ea48-4954-8a1c-22e09d9fdc18")]
            public virtual RepoItemInfo FIRSTBUSInfo
            {
                get
                {
                    return _firstbusInfo;
                }
            }

            /// <summary>
            /// The Get10PercentUptoRs50Off item.
            /// </summary>
            [RepositoryItem("a423863f-b9af-4e21-8852-a65da9fc415f")]
            public virtual Ranorex.SpanTag Get10PercentUptoRs50Off
            {
                get
                {
                    return _get10percentuptors50offInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Get10PercentUptoRs50Off item info.
            /// </summary>
            [RepositoryItemInfo("a423863f-b9af-4e21-8852-a65da9fc415f")]
            public virtual RepoItemInfo Get10PercentUptoRs50OffInfo
            {
                get
                {
                    return _get10percentuptors50offInfo;
                }
            }

            /// <summary>
            /// The MakePayment item.
            /// </summary>
            [RepositoryItem("f9f8df40-3a12-4088-b5f3-130bf220b913")]
            public virtual Ranorex.InputTag MakePayment
            {
                get
                {
                    return _makepaymentInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The MakePayment item info.
            /// </summary>
            [RepositoryItemInfo("f9f8df40-3a12-4088-b5f3-130bf220b913")]
            public virtual RepoItemInfo MakePaymentInfo
            {
                get
                {
                    return _makepaymentInfo;
                }
            }

            /// <summary>
            /// The IconInfoDibIco14GreyDrMarginL10VMi item.
            /// </summary>
            [RepositoryItem("dc53b6b3-296c-45e8-95b5-0bafeb095b83")]
            public virtual Ranorex.ITag IconInfoDibIco14GreyDrMarginL10VMi
            {
                get
                {
                    return _iconinfodibico14greydrmarginl10vmiInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IconInfoDibIco14GreyDrMarginL10VMi item info.
            /// </summary>
            [RepositoryItemInfo("dc53b6b3-296c-45e8-95b5-0bafeb095b83")]
            public virtual RepoItemInfo IconInfoDibIco14GreyDrMarginL10VMiInfo
            {
                get
                {
                    return _iconinfodibico14greydrmarginl10vmiInfo;
                }
            }

            /// <summary>
            /// The NetBanking item.
            /// </summary>
            [RepositoryItem("09bb02be-10e6-45c4-8189-69e6f29d7f2a")]
            public virtual Ranorex.ATag NetBanking
            {
                get
                {
                    return _netbankingInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NetBanking item info.
            /// </summary>
            [RepositoryItemInfo("09bb02be-10e6-45c4-8189-69e6f29d7f2a")]
            public virtual RepoItemInfo NetBankingInfo
            {
                get
                {
                    return _netbankingInfo;
                }
            }

            /// <summary>
            /// The PayNetbRb item.
            /// </summary>
            [RepositoryItem("4c22968c-5703-4149-abcd-38ae27d3ca48")]
            public virtual Ranorex.InputTag PayNetbRb
            {
                get
                {
                    return _paynetbrbInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PayNetbRb item info.
            /// </summary>
            [RepositoryItemInfo("4c22968c-5703-4149-abcd-38ae27d3ca48")]
            public virtual RepoItemInfo PayNetbRbInfo
            {
                get
                {
                    return _paynetbrbInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("6a69210b-0de2-4e39-8217-0f00d692a320")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("6a69210b-0de2-4e39-8217-0f00d692a320")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The HttpsGoibiboIbcdnComStyleguideIma item.
            /// </summary>
            [RepositoryItem("6b173318-99d8-48c5-a3d2-24c2bb0b58b1")]
            public virtual Ranorex.ImgTag HttpsGoibiboIbcdnComStyleguideIma
            {
                get
                {
                    return _httpsgoibiboibcdncomstyleguideimaInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsGoibiboIbcdnComStyleguideIma item info.
            /// </summary>
            [RepositoryItemInfo("6b173318-99d8-48c5-a3d2-24c2bb0b58b1")]
            public virtual RepoItemInfo HttpsGoibiboIbcdnComStyleguideImaInfo
            {
                get
                {
                    return _httpsgoibiboibcdncomstyleguideimaInfo;
                }
            }
        }

        /// <summary>
        /// The StateBankOfIndiaInternetBankingAppFolder folder.
        /// </summary>
        [RepositoryFolder("b5cd388e-6e44-43a0-beb7-32cff957b964")]
        public partial class StateBankOfIndiaInternetBankingAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clickhereInfo;

            /// <summary>
            /// Creates a new StateBankOfIndiaInternetBanking  folder.
            /// </summary>
            public StateBankOfIndiaInternetBankingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("StateBankOfIndiaInternetBanking", "/dom[@domain='merchant.onlinesbi.com']", parentFolder, 30000, null, false, "b5cd388e-6e44-43a0-beb7-32cff957b964", "")
            {
                _clickhereInfo = new RepoItemInfo(this, "ClickHere", ".//div[#'login_block']/div[5]/ul/?/?/a[@innertext='Click here']", 30000, null, "cac7d9b8-7b7d-40ef-92f2-b41e00425f08");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b5cd388e-6e44-43a0-beb7-32cff957b964")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b5cd388e-6e44-43a0-beb7-32cff957b964")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClickHere item.
            /// </summary>
            [RepositoryItem("cac7d9b8-7b7d-40ef-92f2-b41e00425f08")]
            public virtual Ranorex.ATag ClickHere
            {
                get
                {
                    return _clickhereInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ClickHere item info.
            /// </summary>
            [RepositoryItemInfo("cac7d9b8-7b7d-40ef-92f2-b41e00425f08")]
            public virtual RepoItemInfo ClickHereInfo
            {
                get
                {
                    return _clickhereInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}