///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Goibibo_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Cars recording.
    /// </summary>
    [TestModule("1af2b338-5e15-49a0-88b7-b2665205538f", ModuleType.Recording, 1)]
    public partial class Cars : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IF repository.
        /// </summary>
        public static IF repo = IF.Instance;

        static Cars instance = new Cars();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Cars()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Cars Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.IconAirportTransferDbBlueIco24Lh1' at 21;15.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.IconAirportTransferDbBlueIco24Lh1Info, new RecordItemIndex(0));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.IconAirportTransferDbBlueIco24Lh1.Click("21;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.PTagNewDelhi' at 79;9.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.PTagNewDelhiInfo, new RecordItemIndex(1));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.PTagNewDelhi.Click("79;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputL' at 118;15.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(2));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.Click("118;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'del' with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputL'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(3));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.PressKeys("del");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.DelhiCantonmentNewDelhiDelhiIndi' at 106;-1.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.DelhiCantonmentNewDelhiDelhiIndiInfo, new RecordItemIndex(4));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.DelhiCantonmentNewDelhiDelhiIndi.Click("106;-1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Agra' at 85;7.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.AgraInfo, new RecordItemIndex(5));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Agra.Click("85;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputL' at 142;10.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(6));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.Click("142;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'agra' with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputL'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(7));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.PressKeys("agra");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.CustomResult' at 122;5.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.CustomResultInfo, new RecordItemIndex(8));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.CustomResult.Click("122;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Text' at 39;16.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.TextInfo, new RecordItemIndex(9));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Text.Click("39;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton' at 8;4.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButtonInfo, new RecordItemIndex(11));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.DayPickerNavButtonDayPickerNavButton.Click("8;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.DivTag1' at 29;7.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.DivTag1Info, new RecordItemIndex(12));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.DivTag1.Click("29;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.SearchCabs' at 220;10.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.SearchCabsInfo, new RecordItemIndex(13));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.SearchCabs.Click("220;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(15));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(16));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(17));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Sedan' at 69;6.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.SedanInfo, new RecordItemIndex(18));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Sedan.Click("69;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.PTagSuv' at 67;11.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.PTagSuvInfo, new RecordItemIndex(19));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.PTagSuv.Click("67;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(20));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(21));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Hatchback' at 52;10.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.HatchbackInfo, new RecordItemIndex(22));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Hatchback.Click("52;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(23));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.IcongocarsInfoBlueIco20' at 1;10.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.IcongocarsInfoBlueIco20Info, new RecordItemIndex(24));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.IcongocarsInfoBlueIco20.Click("1;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.GOTIT' at 38;6.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.GOTITInfo, new RecordItemIndex(25));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.GOTIT.Click("38;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(26));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.FareDetails' at 18;3.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.FareDetailsInfo, new RecordItemIndex(27));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.FareDetails.Click("18;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(28));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.GOTIT' at 25;4.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.GOTITInfo, new RecordItemIndex(29));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.GOTIT.Click("25;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(30));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 120 units.", new RecordItemIndex(31));
            Mouse.ScrollWheel(120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(32));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.BtnBigBlueWidth100Ico17' at 247;3.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.BtnBigBlueWidth100Ico17Info, new RecordItemIndex(33));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.BtnBigBlueWidth100Ico17.Click("247;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(34));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.PayOptMobTabs' at 474;-20.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.PayOptMobTabsInfo, new RecordItemIndex(35));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.PayOptMobTabs.Click("474;-20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.NetBanking' at 40;11.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.NetBankingInfo, new RecordItemIndex(36));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.NetBanking.Click("40;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.PayNetbRb' at 7;6.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.PayNetbRbInfo, new RecordItemIndex(37));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.PayNetbRb.Click("7;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(38));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Submit' at 130;9.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.SubmitInfo, new RecordItemIndex(39));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Submit.Click("130;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.StateBankOfIndiaInternetBanking.ClickHere' at 15;3.", repo.Hotel.StateBankOfIndiaInternetBanking.ClickHereInfo, new RecordItemIndex(40));
            repo.Hotel.StateBankOfIndiaInternetBanking.ClickHere.Click("15;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.GoibiboLogo' at 48;11.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.GoibiboLogoInfo, new RecordItemIndex(41));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.GoibiboLogo.Click("48;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
