///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Goibibo_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Dom_hotel recording.
    /// </summary>
    [TestModule("fc3adcdb-f4ff-4147-a194-1faa4d6a31f9", ModuleType.Recording, 1)]
    public partial class Dom_hotel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IF repository.
        /// </summary>
        public static IF repo = IF.Instance;

        static Dom_hotel instance = new Dom_hotel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Dom_hotel()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Dom_hotel Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineHotelBookingBookCheapBudge.IconHotelsDbBlueIco28Lh12PadT2Pa' at 27;24.", repo.OnlineHotelBookingBookCheapBudge.IconHotelsDbBlueIco28Lh12PadT2PaInfo, new RecordItemIndex(0));
            repo.OnlineHotelBookingBookCheapBudge.IconHotelsDbBlueIco28Lh12PadT2Pa.Click("27;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineHotelBookingBookCheapBudge.GosuggestInputL' at 77;23.", repo.OnlineHotelBookingBookCheapBudge.GosuggestInputLInfo, new RecordItemIndex(1));
            repo.OnlineHotelBookingBookCheapBudge.GosuggestInputL.Click("77;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'de' with focus on 'OnlineHotelBookingBookCheapBudge.GosuggestInputL'.", repo.OnlineHotelBookingBookCheapBudge.GosuggestInputLInfo, new RecordItemIndex(2));
            repo.OnlineHotelBookingBookCheapBudge.GosuggestInputL.PressKeys("de");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'lhi' with focus on 'OnlineHotelBookingBookCheapBudge.GosuggestInputL'.", repo.OnlineHotelBookingBookCheapBudge.GosuggestInputLInfo, new RecordItemIndex(3));
            repo.OnlineHotelBookingBookCheapBudge.GosuggestInputL.PressKeys("lhi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineHotelBookingBookCheapBudge.ReactAutosuggest1Suggestion0' at 94;6.", repo.OnlineHotelBookingBookCheapBudge.ReactAutosuggest1Suggestion0Info, new RecordItemIndex(4));
            repo.OnlineHotelBookingBookCheapBudge.ReactAutosuggest1Suggestion0.Click("94;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.Text' at 98;8.", repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.TextInfo, new RecordItemIndex(5));
            repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.Text.Click("98;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.DayPickerNavButtonDayPickerNavButton' at 9;8.", repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.DayPickerNavButtonDayPickerNavButtonInfo, new RecordItemIndex(6));
            repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.DayPickerNavButtonDayPickerNavButton.Click("9;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.DivTag9' at 18;24.", repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.DivTag9Info, new RecordItemIndex(7));
            repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.DivTag9.Click("18;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.DivTag10' at 29;14.", repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.DivTag10Info, new RecordItemIndex(8));
            repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.DivTag10.Click("29;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.GetSetGo' at 27;15.", repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.GetSetGoInfo, new RecordItemIndex(9));
            repo.OnlineHotelBookingBookCheapBudge.ColMd12ColSm12ColXs12Pad0.GetSetGo.Click("27;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid0' at 120;3.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid0Info, new RecordItemIndex(11));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid0.Click("120;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1440 units.", new RecordItemIndex(12));
            Mouse.ScrollWheel(-1440);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1320 units.", new RecordItemIndex(13));
            Mouse.ScrollWheel(1320);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid01' at 71;8.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid01Info, new RecordItemIndex(14));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid01.Click("71;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(15));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(16));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid02' at 68;5.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid02Info, new RecordItemIndex(17));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid02.Click("68;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1560 units.", new RecordItemIndex(18));
            Mouse.ScrollWheel(-1560);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1560 units.", new RecordItemIndex(19));
            Mouse.ScrollWheel(1560);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(20));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(21));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid03' at 89;4.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid03Info, new RecordItemIndex(22));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.SrpTabsList.JavascriptVoid03.Click("89;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(23));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(24));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck' at 10;9.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheckInfo, new RecordItemIndex(25));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck.Click("10;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck' at 10;9.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheckInfo, new RecordItemIndex(26));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck.Click("10;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck1' at 6;7.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck1Info, new RecordItemIndex(27));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck1.Click("6;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(28));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(29));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck1' at 7;7.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck1Info, new RecordItemIndex(30));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck1.Click("7;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck2' at 3;6.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck2Info, new RecordItemIndex(31));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck2.Click("3;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(32));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(33));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck2' at 7;5.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck2Info, new RecordItemIndex(34));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck2.Click("7;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(35));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck3' at 6;6.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck3Info, new RecordItemIndex(36));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck3.Click("6;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(37));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(38));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck3' at 6;5.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck3Info, new RecordItemIndex(39));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck3.Click("6;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck4' at 7;5.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck4Info, new RecordItemIndex(40));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck4.Click("7;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(41));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(42));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck4' at 5;4.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck4Info, new RecordItemIndex(43));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck4.Click("5;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck5' at 2;5.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck5Info, new RecordItemIndex(44));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck5.Click("2;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1200 units.", new RecordItemIndex(45));
            Mouse.ScrollWheel(-1200);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(46));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck5' at 8;6.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck5Info, new RecordItemIndex(47));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck5.Click("8;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(48));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(49));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck6' at 7;2.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck6Info, new RecordItemIndex(50));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Width100FlSrpOffrBlkPad10MarginT5.DivCustomCheck6.Click("7;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(51));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(52));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(53));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.BookNow' at 44;12.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.BookNowInfo, new RecordItemIndex(54));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.BookNow.Click("44;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -2400 units.", new RecordItemIndex(55));
            Mouse.ScrollWheel(-2400);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 2400 units.", new RecordItemIndex(56));
            Mouse.ScrollWheel(2400);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1080 units.", new RecordItemIndex(57));
            Mouse.ScrollWheel(-1080);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.Location' at 32;9.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.LocationInfo, new RecordItemIndex(58));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.Location.Click("32;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.GuestReviews' at 67;9.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.GuestReviewsInfo, new RecordItemIndex(59));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.GuestReviews.Click("67;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.QuestionAnswers' at 51;3.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.QuestionAnswersInfo, new RecordItemIndex(60));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.QuestionAnswers.Click("51;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.HotelPolicies' at 32;10.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.HotelPoliciesInfo, new RecordItemIndex(61));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Menubar.HotelPolicies.Click("32;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 11280 units.", new RecordItemIndex(62));
            Mouse.ScrollWheel(11280);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(63));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.BookNow1' at 64;22.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.BookNow1Info, new RecordItemIndex(64));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.BookNow1.Click("64;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(65));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(66));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(67));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.CancelPolicyLinkV3' at 79;6.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.CancelPolicyLinkV3Info, new RecordItemIndex(68));
            //repo.Hotel.OnlineFlightBookingHotelsBusAmp.CancelPolicyLinkV3.Click("79;6");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.JavascriptVoid04' at 3;3.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.JavascriptVoid04Info, new RecordItemIndex(69));
            //repo.Hotel.OnlineFlightBookingHotelsBusAmp.JavascriptVoid04.Click("3;3");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(70));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.FULLREFUNDHOTELSURPRISE' at 10;4.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.FULLREFUNDHOTELSURPRISEInfo, new RecordItemIndex(71));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.FULLREFUNDHOTELSURPRISE.Click("10;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.ButtonTagOk' at 16;6.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.ButtonTagOkInfo, new RecordItemIndex(72));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.ButtonTagOk.Click("16;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.FULLREFUNDCASHBACK' at 7;4.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.FULLREFUNDCASHBACKInfo, new RecordItemIndex(73));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.FULLREFUNDCASHBACK.Click("7;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.ButtonTagOk' at 5;13.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.ButtonTagOkInfo, new RecordItemIndex(74));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.ButtonTagOk.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.FULLREFUNDHDFCH5X' at 6;9.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.FULLREFUNDHDFCH5XInfo, new RecordItemIndex(75));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.FULLREFUNDHDFCH5X.Click("6;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.ButtonTagOk' at 8;12.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.ButtonTagOkInfo, new RecordItemIndex(76));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.ButtonTagOk.Click("8;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(77));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'Hotel.OnlineFlightBookingHotelsBusAmp.Choose'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.ChooseInfo, new RecordItemIndex(78));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Choose.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1' at 86;27.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1Info, new RecordItemIndex(79));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1.Click("86;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}' with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1Info, new RecordItemIndex(80));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1.PressKeys("{LControlKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.Lastname1'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Lastname1Info, new RecordItemIndex(81));
            Keyboard.PrepareFocus(repo.Hotel.OnlineFlightBookingHotelsBusAmp.Lastname1);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1Info, new RecordItemIndex(82));
            Keyboard.PrepareFocus(repo.Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}Devendra' with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1Info, new RecordItemIndex(83));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Firstname1.PressKeys("{Back}Devendra");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Lastname1' at 55;22.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Lastname1Info, new RecordItemIndex(84));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Lastname1.Click("55;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}Gupta' with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.Lastname1'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.Lastname1Info, new RecordItemIndex(85));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Lastname1.PressKeys("{Back}Gupta");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Email' at 212;14.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.EmailInfo, new RecordItemIndex(86));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Email.Click("212;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.Email'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.EmailInfo, new RecordItemIndex(87));
            Keyboard.PrepareFocus(repo.Hotel.OnlineFlightBookingHotelsBusAmp.Email);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com' with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.Email'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.EmailInfo, new RecordItemIndex(88));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Email.PressKeys("{Back}testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Mobile' at 99;12.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.MobileInfo, new RecordItemIndex(89));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Mobile.Click("99;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.Mobile'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.MobileInfo, new RecordItemIndex(90));
            Keyboard.PrepareFocus(repo.Hotel.OnlineFlightBookingHotelsBusAmp.Mobile);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}9999999999' with focus on 'Hotel.OnlineFlightBookingHotelsBusAmp.Mobile'.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.MobileInfo, new RecordItemIndex(91));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Mobile.PressKeys("{Back}9999999999");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.MakePayment' at 116;15.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.MakePaymentInfo, new RecordItemIndex(92));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.MakePayment.Click("116;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(93));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(94));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(95));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(96));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(97));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(98));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(99));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(100));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(101));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(102));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(103));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(104));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(105));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(106));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -960 units.", new RecordItemIndex(107));
            Mouse.ScrollWheel(-960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(108));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -960 units.", new RecordItemIndex(109));
            Mouse.ScrollWheel(-960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(110));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(111));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(112));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(113));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(114));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(115));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(116));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -960 units.", new RecordItemIndex(117));
            Mouse.ScrollWheel(-960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(118));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -960 units.", new RecordItemIndex(119));
            Mouse.ScrollWheel(-960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(120));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -960 units.", new RecordItemIndex(121));
            Mouse.ScrollWheel(-960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(122));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -960 units.", new RecordItemIndex(123));
            Mouse.ScrollWheel(-960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(124));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -960 units.", new RecordItemIndex(125));
            Mouse.ScrollWheel(-960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 120 units.", new RecordItemIndex(126));
            Mouse.ScrollWheel(120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(127));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(128));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(129));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(130));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(131));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(132));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(133));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(134));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(135));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(136));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(137));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.NetBanking' at 18;15.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.NetBankingInfo, new RecordItemIndex(138));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.NetBanking.Click("18;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.AmazonPay' at 22;13.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.AmazonPayInfo, new RecordItemIndex(139));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.AmazonPay.Click("22;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.PayPal' at 12;19.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.PayPalInfo, new RecordItemIndex(140));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.PayPal.Click("12;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.NetBanking' at 50;11.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.NetBankingInfo, new RecordItemIndex(141));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.TabnavOpts.NetBanking.Click("50;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.PayNetbRb' at 5;6.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.PayNetbRbInfo, new RecordItemIndex(142));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.PayNetbRb.Click("5;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(143));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.Submit' at 220;22.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.SubmitInfo, new RecordItemIndex(144));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.Submit.Click("220;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(145));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.StateBankOfIndiaInternetBanking.ClickHere' at 21;4.", repo.Hotel.StateBankOfIndiaInternetBanking.ClickHereInfo, new RecordItemIndex(146));
            repo.Hotel.StateBankOfIndiaInternetBanking.ClickHere.Click("21;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotel.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma' at 40;10.", repo.Hotel.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideImaInfo, new RecordItemIndex(147));
            repo.Hotel.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma.Click("40;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
