///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Goibibo_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Dom_Flight recording.
    /// </summary>
    [TestModule("6d927d2b-48d5-4102-b89d-9aa6a9cd7e5a", ModuleType.Recording, 1)]
    public partial class Dom_Flight : ITestModule
    {
        /// <summary>
        /// Holds an instance of the FlightRepo repository.
        /// </summary>
        public static FlightRepo repo = FlightRepo.Instance;

        static Dom_Flight instance = new Dom_Flight();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Dom_Flight()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Dom_Flight Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.IconFlightsDbBlueIco24Lh12PadT5P' at 25;27.", repo.OnlineFlightBookingHotelsBusAmp.IconFlightsDbBlueIco24Lh12PadT5PInfo, new RecordItemIndex(0));
            repo.OnlineFlightBookingHotelsBusAmp.IconFlightsDbBlueIco24Lh12PadT5P.Click("25;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc' at 59;21.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(1));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc.Click("59;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'de' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrcInfo, new RecordItemIndex(2));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputSrc.PressKeys("de");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SpanTagDEL' at 4;4.", repo.OnlineFlightBookingHotelsBusAmp.SpanTagDELInfo, new RecordItemIndex(3));
            repo.OnlineFlightBookingHotelsBusAmp.SpanTagDEL.Click("4;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest' at 69;30.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(4));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.Click("69;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'banga' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputDest'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDestInfo, new RecordItemIndex(5));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputDest.PressKeys("banga");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Bangalore' at 27;6.", repo.OnlineFlightBookingHotelsBusAmp.BangaloreInfo, new RecordItemIndex(6));
            repo.OnlineFlightBookingHotelsBusAmp.Bangalore.Click("27;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(7));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Fare20190118' at 14;12.", repo.OnlineFlightBookingHotelsBusAmp.Fare20190118Info, new RecordItemIndex(8));
            repo.OnlineFlightBookingHotelsBusAmp.Fare20190118.Click("14;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.PaxLabel' at 89;15.", repo.OnlineFlightBookingHotelsBusAmp.PaxLabelInfo, new RecordItemIndex(9));
            repo.OnlineFlightBookingHotelsBusAmp.PaxLabel.Click("89;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AdultPaxPlus' at 24;9.", repo.OnlineFlightBookingHotelsBusAmp.AdultPaxPlusInfo, new RecordItemIndex(10));
            repo.OnlineFlightBookingHotelsBusAmp.AdultPaxPlus.Click("24;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AdultPaxPlus' at 24;9.", repo.OnlineFlightBookingHotelsBusAmp.AdultPaxPlusInfo, new RecordItemIndex(11));
            repo.OnlineFlightBookingHotelsBusAmp.AdultPaxPlus.Click("24;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AdultPaxMinus' at 17;11.", repo.OnlineFlightBookingHotelsBusAmp.AdultPaxMinusInfo, new RecordItemIndex(12));
            repo.OnlineFlightBookingHotelsBusAmp.AdultPaxMinus.Click("17;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AdultPaxMinus' at 17;11.", repo.OnlineFlightBookingHotelsBusAmp.AdultPaxMinusInfo, new RecordItemIndex(13));
            repo.OnlineFlightBookingHotelsBusAmp.AdultPaxMinus.Click("17;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.PaxClose' at 4;4.", repo.OnlineFlightBookingHotelsBusAmp.PaxCloseInfo, new RecordItemIndex(14));
            repo.OnlineFlightBookingHotelsBusAmp.PaxClose.Click("4;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GiSearchBtn' at 104;16.", repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtnInfo, new RecordItemIndex(15));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtn.Click("104;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(16));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1200 units.", new RecordItemIndex(17));
            Mouse.ScrollWheel(1200);
            Delay.Milliseconds(500);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunriseIco24' at 49;19.", repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunriseIco24Info, new RecordItemIndex(18));
            //repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunriseIco24.Click("49;19");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunIco24' at 55;10.", repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunIco24Info, new RecordItemIndex(19));
            //repo.OnlineFlightBookingHotelsBusAmp.DbGreyDrIconSunIco24.Click("55;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NavSectionTabs.ResetFilters' at 90;8.", repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.ResetFiltersInfo, new RecordItemIndex(20));
            //repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.ResetFilters.Click("90;8");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Stops' at 25;14.", repo.OnlineFlightBookingHotelsBusAmp.StopsInfo, new RecordItemIndex(21));
            repo.OnlineFlightBookingHotelsBusAmp.Stops.Click("25;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NavSectionTabs.NonStop' at 12;6.", repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.NonStopInfo, new RecordItemIndex(22));
            repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.NonStop.Click("12;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NavSectionTabs.LabelTag1Stop' at 7;4.", repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.LabelTag1StopInfo, new RecordItemIndex(23));
            repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.LabelTag1Stop.Click("7;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NavSectionTabs.AllStops' at 7;11.", repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.AllStopsInfo, new RecordItemIndex(24));
            repo.OnlineFlightBookingHotelsBusAmp.NavSectionTabs.AllStops.Click("7;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(25));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(26));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Price' at 7;8.", repo.OnlineFlightBookingHotelsBusAmp.PriceInfo, new RecordItemIndex(27));
            repo.OnlineFlightBookingHotelsBusAmp.Price.Click("7;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(28));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(29));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.FlIconInfoIco11Black' at 1;5.", repo.OnlineFlightBookingHotelsBusAmp.Header.FlIconInfoIco11BlackInfo, new RecordItemIndex(30));
            repo.OnlineFlightBookingHotelsBusAmp.Header.FlIconInfoIco11Black.Click("1;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.FlightDetails' at 24;9.", repo.OnlineFlightBookingHotelsBusAmp.Header.FlightDetailsInfo, new RecordItemIndex(31));
            repo.OnlineFlightBookingHotelsBusAmp.Header.FlightDetails.Click("24;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(32));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.FareDetails' at 53;21.", repo.OnlineFlightBookingHotelsBusAmp.Header.FareDetailsInfo, new RecordItemIndex(33));
            repo.OnlineFlightBookingHotelsBusAmp.Header.FareDetails.Click("53;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.BaggageInformation' at 65;19.", repo.OnlineFlightBookingHotelsBusAmp.Header.BaggageInformationInfo, new RecordItemIndex(34));
            repo.OnlineFlightBookingHotelsBusAmp.Header.BaggageInformation.Click("65;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.CancellationRules' at 41;12.", repo.OnlineFlightBookingHotelsBusAmp.Header.CancellationRulesInfo, new RecordItemIndex(35));
            repo.OnlineFlightBookingHotelsBusAmp.Header.CancellationRules.Click("41;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(36));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(37));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.FlIconClose1Ico20' at 6;12.", repo.OnlineFlightBookingHotelsBusAmp.Header.FlIconClose1Ico20Info, new RecordItemIndex(38));
            repo.OnlineFlightBookingHotelsBusAmp.Header.FlIconClose1Ico20.Click("6;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(39));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(40));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.Button' at 27;9.", repo.OnlineFlightBookingHotelsBusAmp.Header.ButtonInfo, new RecordItemIndex(41));
            repo.OnlineFlightBookingHotelsBusAmp.Header.Button.Click("27;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(42));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(43));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(44));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRules' at 62;14.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRulesInfo, new RecordItemIndex(45));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.BaggageAndFareRules.Click("62;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FltFareRulesTab' at 65;10.", repo.OnlineFlightBookingHotelsBusAmp.FltFareRulesTabInfo, new RecordItemIndex(46));
            repo.OnlineFlightBookingHotelsBusAmp.FltFareRulesTab.Click("65;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(47));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(48));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.JavascriptVoid0' at 5;1.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.JavascriptVoid0Info, new RecordItemIndex(49));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.JavascriptVoid0.Click("5;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(50));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.OfferScroll.IconQuestionOp07Ico14FlPadT2PadL5' at 13;5.", repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.IconQuestionOp07Ico14FlPadT2PadL5Info, new RecordItemIndex(51));
            repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.IconQuestionOp07Ico14FlPadT2PadL5.Click("13;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.OfferScroll.IconQuestionOp07Ico14FlPadT2PadL51' at 11;8.", repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.IconQuestionOp07Ico14FlPadT2PadL51Info, new RecordItemIndex(52));
            repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.IconQuestionOp07Ico14FlPadT2PadL51.Click("11;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(53));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.OfferScroll.Remove' at 32;3.", repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.RemoveInfo, new RecordItemIndex(54));
            repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.Remove.Click("32;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle' at 7;12.", repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddleInfo, new RecordItemIndex(55));
            repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle.Click("7;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOK' at 16;8.", repo.OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOKInfo, new RecordItemIndex(56));
            repo.OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOK.Click("16;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle1' at 11;4.", repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle1Info, new RecordItemIndex(57));
            repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle1.Click("11;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOK' at 14;9.", repo.OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOKInfo, new RecordItemIndex(58));
            repo.OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOK.Click("14;9");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle2' at 8;6.", repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle2Info, new RecordItemIndex(59));
            //repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle2.Click("8;6");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOK' at 26;10.", repo.OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOKInfo, new RecordItemIndex(60));
            //repo.OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOK.Click("26;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(61));
            //Mouse.ScrollWheel(-240);
            //Delay.Milliseconds(500);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle3' at 10;5.", repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle3Info, new RecordItemIndex(62));
            //repo.OnlineFlightBookingHotelsBusAmp.OfferScroll.ControlIndicatorVMiddle3.Click("10;5");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOK' at 19;10.", repo.OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOKInfo, new RecordItemIndex(63));
            //repo.OnlineFlightBookingHotelsBusAmp.Header.ButtonTagOK.Click("19;10");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.CancellationRadio' at 8;3.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.CancellationRadioInfo, new RecordItemIndex(64));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.CancellationRadio.Click("8;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(65));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(66));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.CancellationRadio' at 5;10.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.CancellationRadioInfo, new RecordItemIndex(67));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.CancellationRadio.Click("5;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 480 units.", new RecordItemIndex(68));
            Mouse.ScrollWheel(480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1320 units.", new RecordItemIndex(69));
            Mouse.ScrollWheel(-1320);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadio' at 2;11.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadioInfo, new RecordItemIndex(70));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadio.Click("2;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadio' at 2;11.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadioInfo, new RecordItemIndex(71));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadio.Click("2;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(72));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'OnlineFlightBookingHotelsBusAmp.Adulttitle1'.", repo.OnlineFlightBookingHotelsBusAmp.Adulttitle1Info, new RecordItemIndex(73));
            repo.OnlineFlightBookingHotelsBusAmp.Adulttitle1.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AdultfirstName1' at 79;23.", repo.OnlineFlightBookingHotelsBusAmp.AdultfirstName1Info, new RecordItemIndex(74));
            repo.OnlineFlightBookingHotelsBusAmp.AdultfirstName1.Click("79;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Devendra' with focus on 'OnlineFlightBookingHotelsBusAmp.AdultfirstName1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultfirstName1Info, new RecordItemIndex(75));
            repo.OnlineFlightBookingHotelsBusAmp.AdultfirstName1.PressKeys("Devendra");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AdultlastName1' at 31;18.", repo.OnlineFlightBookingHotelsBusAmp.AdultlastName1Info, new RecordItemIndex(76));
            repo.OnlineFlightBookingHotelsBusAmp.AdultlastName1.Click("31;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Gupta' with focus on 'OnlineFlightBookingHotelsBusAmp.AdultlastName1'.", repo.OnlineFlightBookingHotelsBusAmp.AdultlastName1Info, new RecordItemIndex(77));
            repo.OnlineFlightBookingHotelsBusAmp.AdultlastName1.PressKeys("Gupta");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Email' at 246;13.", repo.OnlineFlightBookingHotelsBusAmp.EmailInfo, new RecordItemIndex(78));
            repo.OnlineFlightBookingHotelsBusAmp.Email.Click("246;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com' with focus on 'OnlineFlightBookingHotelsBusAmp.Email'.", repo.OnlineFlightBookingHotelsBusAmp.EmailInfo, new RecordItemIndex(79));
            repo.OnlineFlightBookingHotelsBusAmp.Email.PressKeys("testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Mobile' at 130;15.", repo.OnlineFlightBookingHotelsBusAmp.MobileInfo, new RecordItemIndex(80));
            repo.OnlineFlightBookingHotelsBusAmp.Mobile.Click("130;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9999999999' with focus on 'OnlineFlightBookingHotelsBusAmp.Mobile'.", repo.OnlineFlightBookingHotelsBusAmp.MobileInfo, new RecordItemIndex(81));
            repo.OnlineFlightBookingHotelsBusAmp.Mobile.PressKeys("9999999999");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.ProceedToPayment' at 101;18.", repo.OnlineFlightBookingHotelsBusAmp.ProceedToPaymentInfo, new RecordItemIndex(82));
            repo.OnlineFlightBookingHotelsBusAmp.ProceedToPayment.Click("101;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(83));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(84));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(85));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NetBanking' at 35;12.", repo.OnlineFlightBookingHotelsBusAmp.NetBankingInfo, new RecordItemIndex(86));
            repo.OnlineFlightBookingHotelsBusAmp.NetBanking.Click("35;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(87));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.UpiTab' at 16;12.", repo.OnlineFlightBookingHotelsBusAmp.UpiTabInfo, new RecordItemIndex(88));
            repo.OnlineFlightBookingHotelsBusAmp.UpiTab.Click("16;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.TezTab' at 36;9.", repo.OnlineFlightBookingHotelsBusAmp.TezTabInfo, new RecordItemIndex(89));
            repo.OnlineFlightBookingHotelsBusAmp.TezTab.Click("36;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NetBanking' at 35;7.", repo.OnlineFlightBookingHotelsBusAmp.NetBankingInfo, new RecordItemIndex(90));
            repo.OnlineFlightBookingHotelsBusAmp.NetBanking.Click("35;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.AmazonPay' at 28;13.", repo.OnlineFlightBookingHotelsBusAmp.AmazonPayInfo, new RecordItemIndex(91));
            repo.OnlineFlightBookingHotelsBusAmp.AmazonPay.Click("28;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NetBanking' at 39;10.", repo.OnlineFlightBookingHotelsBusAmp.NetBankingInfo, new RecordItemIndex(92));
            repo.OnlineFlightBookingHotelsBusAmp.NetBanking.Click("39;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.PayNetbRb' at 7;5.", repo.OnlineFlightBookingHotelsBusAmp.PayNetbRbInfo, new RecordItemIndex(93));
            repo.OnlineFlightBookingHotelsBusAmp.PayNetbRb.Click("7;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Submit' at 175;13.", repo.OnlineFlightBookingHotelsBusAmp.SubmitInfo, new RecordItemIndex(94));
            repo.OnlineFlightBookingHotelsBusAmp.Submit.Click("175;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(95));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StateBankOfIndiaInternetBanking.ClickHere' at 11;1.", repo.StateBankOfIndiaInternetBanking.ClickHereInfo, new RecordItemIndex(96));
            repo.StateBankOfIndiaInternetBanking.ClickHere.Click("11;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma' at 51;10.", repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideImaInfo, new RecordItemIndex(97));
            repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma.Click("51;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
