///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Goibibo_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FlightRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("b67f9c1c-058d-45ca-a796-07c1fbf4c5ca")]
    public partial class FlightRepo : RepoGenBaseFolder
    {
        static FlightRepo instance = new FlightRepo();
        FlightRepoFolders.FlightFolder _flight;
        FlightRepoFolders.OnlineFlightBookingHotelsBusAmpAppFolder _onlineflightbookinghotelsbusamp;
        FlightRepoFolders.StateBankOfIndiaInternetBankingAppFolder _statebankofindiainternetbanking;

        /// <summary>
        /// Gets the singleton class instance representing the FlightRepo element repository.
        /// </summary>
        [RepositoryFolder("b67f9c1c-058d-45ca-a796-07c1fbf4c5ca")]
        public static FlightRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FlightRepo() 
            : base("FlightRepo", "/", null, 0, false, "b67f9c1c-058d-45ca-a796-07c1fbf4c5ca", ".\\RepositoryImages\\FlightRepob67f9c1c.rximgres")
        {
            _flight = new FlightRepoFolders.FlightFolder(this);
            _onlineflightbookinghotelsbusamp = new FlightRepoFolders.OnlineFlightBookingHotelsBusAmpAppFolder(this);
            _statebankofindiainternetbanking = new FlightRepoFolders.StateBankOfIndiaInternetBankingAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b67f9c1c-058d-45ca-a796-07c1fbf4c5ca")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Flight folder.
        /// </summary>
        [RepositoryFolder("21daaaf0-266c-40d2-be7a-7b8391618844")]
        public virtual FlightRepoFolders.FlightFolder Flight
        {
            get { return _flight; }
        }

        /// <summary>
        /// The OnlineFlightBookingHotelsBusAmp folder.
        /// </summary>
        [RepositoryFolder("4c1c00ee-4687-4f6f-aa05-a67227ee2dc9")]
        public virtual FlightRepoFolders.OnlineFlightBookingHotelsBusAmpAppFolder OnlineFlightBookingHotelsBusAmp
        {
            get { return _onlineflightbookinghotelsbusamp; }
        }

        /// <summary>
        /// The StateBankOfIndiaInternetBanking folder.
        /// </summary>
        [RepositoryFolder("4e5f6800-6471-4fca-bb4f-97527b34ee83")]
        public virtual FlightRepoFolders.StateBankOfIndiaInternetBankingAppFolder StateBankOfIndiaInternetBanking
        {
            get { return _statebankofindiainternetbanking; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class FlightRepoFolders
    {
        /// <summary>
        /// The FlightFolder folder.
        /// </summary>
        [RepositoryFolder("21daaaf0-266c-40d2-be7a-7b8391618844")]
        public partial class FlightFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Flight  folder.
            /// </summary>
            public FlightFolder(RepoGenBaseFolder parentFolder) :
                    base("Flight", "", parentFolder, 0, null, false, "21daaaf0-266c-40d2-be7a-7b8391618844", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21daaaf0-266c-40d2-be7a-7b8391618844")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The OnlineFlightBookingHotelsBusAmpAppFolder folder.
        /// </summary>
        [RepositoryFolder("4c1c00ee-4687-4f6f-aa05-a67227ee2dc9")]
        public partial class OnlineFlightBookingHotelsBusAmpAppFolder : RepoGenBaseFolder
        {
            FlightRepoFolders.FlightDetailsFlFolder _flightdetailsfl;
            FlightRepoFolders.HeaderFolder _header;
            FlightRepoFolders.OfferScrollFolder _offerscroll;
            FlightRepoFolders.NavSectionTabsFolder _navsectiontabs;
            RepoItemInfo _iconflightsdbblueico24lh12padt5pInfo;
            RepoItemInfo _gosuggestinputsrcInfo;
            RepoItemInfo _spantagdelInfo;
            RepoItemInfo _gosuggestinputdestInfo;
            RepoItemInfo _bangaloreInfo;
            RepoItemInfo _fare20190118Info;
            RepoItemInfo _paxlabelInfo;
            RepoItemInfo _adultpaxplusInfo;
            RepoItemInfo _adultpaxminusInfo;
            RepoItemInfo _paxcloseInfo;
            RepoItemInfo _gisearchbtnInfo;
            RepoItemInfo _dbgreydriconsunriseico24Info;
            RepoItemInfo _dbgreydriconsunico24Info;
            RepoItemInfo _stopsInfo;
            RepoItemInfo _priceInfo;
            RepoItemInfo _fltfarerulestabInfo;
            RepoItemInfo _adulttitle1Info;
            RepoItemInfo _adultfirstname1Info;
            RepoItemInfo _adultlastname1Info;
            RepoItemInfo _emailInfo;
            RepoItemInfo _mobileInfo;
            RepoItemInfo _proceedtopaymentInfo;
            RepoItemInfo _netbankingInfo;
            RepoItemInfo _upitabInfo;
            RepoItemInfo _teztabInfo;
            RepoItemInfo _amazonpayInfo;
            RepoItemInfo _paynetbrbInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _httpsgoibiboibcdncomstyleguideimaInfo;

            /// <summary>
            /// Creates a new OnlineFlightBookingHotelsBusAmp  folder.
            /// </summary>
            public OnlineFlightBookingHotelsBusAmpAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OnlineFlightBookingHotelsBusAmp", "/dom[@domain='www.goibibo.com']", parentFolder, 30000, null, false, "4c1c00ee-4687-4f6f-aa05-a67227ee2dc9", "")
            {
                _flightdetailsfl = new FlightRepoFolders.FlightDetailsFlFolder(this);
                _header = new FlightRepoFolders.HeaderFolder(this);
                _offerscroll = new FlightRepoFolders.OfferScrollFolder(this);
                _navsectiontabs = new FlightRepoFolders.NavSectionTabsFolder(this);
                _iconflightsdbblueico24lh12padt5pInfo = new RepoItemInfo(this, "IconFlightsDbBlueIco24Lh12PadT5P", ".//div[#'header']/div[1]/ul//i", 30000, null, "f6568bee-191f-4ad0-9732-ff983d16229d");
                _gosuggestinputsrcInfo = new RepoItemInfo(this, "GosuggestInputSrc", ".//input[#'gosuggest_inputSrc']", 30000, null, "c57c83c5-f836-4236-a7a4-6e76f34f732f");
                _spantagdelInfo = new RepoItemInfo(this, "SpanTagDEL", ".//li[#'react-autosuggest-1-suggestion--0']/div/div[2]/div[1]/span[@innertext='(DEL)']", 30000, null, "c4714596-74f4-4b22-a06f-73eff6b8fe5c");
                _gosuggestinputdestInfo = new RepoItemInfo(this, "GosuggestInputDest", ".//input[#'gosuggest_inputDest']", 30000, null, "16c2ddc8-48a0-4b89-afa0-d5c64b4606fc");
                _bangaloreInfo = new RepoItemInfo(this, "Bangalore", ".//li[#'react-autosuggest-1-suggestion--0']/div/div[2]/div[1]/span[@innertext='Bangalore']", 30000, null, "e1beb91f-1e7f-44cd-b5b1-35fef75a7ff6");
                _fare20190118Info = new RepoItemInfo(this, "Fare20190118", ".//div[#'fare_20190118']", 30000, null, "d48655c5-a1b0-42be-863a-cbfd3997ed4f");
                _paxlabelInfo = new RepoItemInfo(this, "PaxLabel", ".//span[#'pax_label']", 30000, null, "6aad7c8a-967e-4986-98f4-e6f43c2880c2");
                _adultpaxplusInfo = new RepoItemInfo(this, "AdultPaxPlus", ".//button[#'adultPaxPlus']", 30000, null, "fee1095f-ef3d-439d-b6a3-0758258e74c3");
                _adultpaxminusInfo = new RepoItemInfo(this, "AdultPaxMinus", ".//button[#'adultPaxMinus']", 30000, null, "7a238ce6-9d00-4157-a08d-5376e08af7a2");
                _paxcloseInfo = new RepoItemInfo(this, "PaxClose", ".//a[#'pax_close']", 30000, null, "830cc4fb-e2da-44b5-8f01-5abec5afad40");
                _gisearchbtnInfo = new RepoItemInfo(this, "GiSearchBtn", ".//button[#'gi_search_btn']", 30000, null, "b3a2faf9-b485-46b5-ab61-20529ef8a26a");
                _dbgreydriconsunriseico24Info = new RepoItemInfo(this, "DbGreyDrIconSunriseIco24", ".//span[#'onw_before11']/i", 30000, null, "ddf4aef6-2d02-4221-8495-ca9de27990a8");
                _dbgreydriconsunico24Info = new RepoItemInfo(this, "DbGreyDrIconSunIco24", ".//span[#'onw_11-5']/i", 30000, null, "b4306105-411d-443d-9290-e0e7a326526f");
                _stopsInfo = new RepoItemInfo(this, "Stops", ".//a[#'stopsFilter']/?/?/span[@innertext='Stops']", 30000, null, "7ff5b8cf-a648-4ccd-ab93-35f5f325ce73");
                _priceInfo = new RepoItemInfo(this, "Price", ".//a[#'pricesFilter']/?/?/span[@innertext='Price']", 30000, null, "d6553973-f152-49cb-a981-2fae2a2b3ed9");
                _fltfarerulestabInfo = new RepoItemInfo(this, "FltFareRulesTab", ".//a[#'fltFareRulesTab']", 30000, null, "78a5cc3c-786f-464e-99a6-8844e0c3c4a1");
                _adulttitle1Info = new RepoItemInfo(this, "Adulttitle1", ".//select[#'Adulttitle1']", 30000, null, "be931ddf-b478-4aa1-af20-a497c4c4d2c0");
                _adultfirstname1Info = new RepoItemInfo(this, "AdultfirstName1", ".//input[#'AdultfirstName1']", 30000, null, "7cbcc8da-10ee-4a9e-adea-f32678e89022");
                _adultlastname1Info = new RepoItemInfo(this, "AdultlastName1", ".//input[#'AdultlastName1']", 30000, null, "f1fbde7c-0771-4314-bf70-04b87d1f7b7d");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "8242e0ba-024c-4908-87e0-593a0223b0f4");
                _mobileInfo = new RepoItemInfo(this, "Mobile", ".//input[#'mobile']", 30000, null, "a3d5fdda-f762-4972-a080-c562b72b48e5");
                _proceedtopaymentInfo = new RepoItemInfo(this, "ProceedToPayment", ".//form[#'travellerForm']/?/?/button[@innertext='Proceed to Payment']", 30000, null, "c9947627-e930-42aa-8e59-65bd6041d1d0");
                _netbankingInfo = new RepoItemInfo(this, "NetBanking", ".//ul[#'tabnav_opts']/?/?/a[@innertext='Net Banking']", 30000, null, "ce90ca85-39f7-41f9-b80d-e0ac834746e1");
                _upitabInfo = new RepoItemInfo(this, "UpiTab", ".//a[#'upi_tab']", 30000, null, "f1b7a876-c9ba-478d-812b-b7ca92b1d2c8");
                _teztabInfo = new RepoItemInfo(this, "TezTab", ".//a[#'tez_tab']", 30000, null, "f60d3afa-272e-40d0-9529-4db81d598524");
                _amazonpayInfo = new RepoItemInfo(this, "AmazonPay", ".//ul[#'tabnav_opts']/?/?/a[@innertext~'^Amazon\\ Pay\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']", 30000, null, "34646ad6-c4f9-440b-9f7d-70ad87d47bf4");
                _paynetbrbInfo = new RepoItemInfo(this, "PayNetbRb", ".//div[#'netBank']/div[2]/div[6]/?/?/input[@name='pay_netb_rb']", 30000, null, "b1c09520-65f0-4e59-ab39-a3c98e3fc2b4");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'netBank']/div[3]/div[4]/?/?/input[@type='submit']", 30000, null, "03185af2-7a5a-48f4-ab86-436bfc6236a3");
                _httpsgoibiboibcdncomstyleguideimaInfo = new RepoItemInfo(this, "HttpsGoibiboIbcdnComStyleguideIma", "body/div[1]/?/?/a[@href='https://www.goibibo.com/']/img[@src='https://goibibo.ibcdn.com/styleguide/images/goLogo.png']", 30000, null, "da65804f-430a-45cd-8221-ece9b4d015a0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4c1c00ee-4687-4f6f-aa05-a67227ee2dc9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4c1c00ee-4687-4f6f-aa05-a67227ee2dc9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IconFlightsDbBlueIco24Lh12PadT5P item.
            /// </summary>
            [RepositoryItem("f6568bee-191f-4ad0-9732-ff983d16229d")]
            public virtual Ranorex.ITag IconFlightsDbBlueIco24Lh12PadT5P
            {
                get
                {
                    return _iconflightsdbblueico24lh12padt5pInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IconFlightsDbBlueIco24Lh12PadT5P item info.
            /// </summary>
            [RepositoryItemInfo("f6568bee-191f-4ad0-9732-ff983d16229d")]
            public virtual RepoItemInfo IconFlightsDbBlueIco24Lh12PadT5PInfo
            {
                get
                {
                    return _iconflightsdbblueico24lh12padt5pInfo;
                }
            }

            /// <summary>
            /// The GosuggestInputSrc item.
            /// </summary>
            [RepositoryItem("c57c83c5-f836-4236-a7a4-6e76f34f732f")]
            public virtual Ranorex.InputTag GosuggestInputSrc
            {
                get
                {
                    return _gosuggestinputsrcInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GosuggestInputSrc item info.
            /// </summary>
            [RepositoryItemInfo("c57c83c5-f836-4236-a7a4-6e76f34f732f")]
            public virtual RepoItemInfo GosuggestInputSrcInfo
            {
                get
                {
                    return _gosuggestinputsrcInfo;
                }
            }

            /// <summary>
            /// The SpanTagDEL item.
            /// </summary>
            [RepositoryItem("c4714596-74f4-4b22-a06f-73eff6b8fe5c")]
            public virtual Ranorex.SpanTag SpanTagDEL
            {
                get
                {
                    return _spantagdelInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagDEL item info.
            /// </summary>
            [RepositoryItemInfo("c4714596-74f4-4b22-a06f-73eff6b8fe5c")]
            public virtual RepoItemInfo SpanTagDELInfo
            {
                get
                {
                    return _spantagdelInfo;
                }
            }

            /// <summary>
            /// The GosuggestInputDest item.
            /// </summary>
            [RepositoryItem("16c2ddc8-48a0-4b89-afa0-d5c64b4606fc")]
            public virtual Ranorex.InputTag GosuggestInputDest
            {
                get
                {
                    return _gosuggestinputdestInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GosuggestInputDest item info.
            /// </summary>
            [RepositoryItemInfo("16c2ddc8-48a0-4b89-afa0-d5c64b4606fc")]
            public virtual RepoItemInfo GosuggestInputDestInfo
            {
                get
                {
                    return _gosuggestinputdestInfo;
                }
            }

            /// <summary>
            /// The Bangalore item.
            /// </summary>
            [RepositoryItem("e1beb91f-1e7f-44cd-b5b1-35fef75a7ff6")]
            public virtual Ranorex.SpanTag Bangalore
            {
                get
                {
                    return _bangaloreInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Bangalore item info.
            /// </summary>
            [RepositoryItemInfo("e1beb91f-1e7f-44cd-b5b1-35fef75a7ff6")]
            public virtual RepoItemInfo BangaloreInfo
            {
                get
                {
                    return _bangaloreInfo;
                }
            }

            /// <summary>
            /// The Fare20190118 item.
            /// </summary>
            [RepositoryItem("d48655c5-a1b0-42be-863a-cbfd3997ed4f")]
            public virtual Ranorex.DivTag Fare20190118
            {
                get
                {
                    return _fare20190118Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Fare20190118 item info.
            /// </summary>
            [RepositoryItemInfo("d48655c5-a1b0-42be-863a-cbfd3997ed4f")]
            public virtual RepoItemInfo Fare20190118Info
            {
                get
                {
                    return _fare20190118Info;
                }
            }

            /// <summary>
            /// The PaxLabel item.
            /// </summary>
            [RepositoryItem("6aad7c8a-967e-4986-98f4-e6f43c2880c2")]
            public virtual Ranorex.SpanTag PaxLabel
            {
                get
                {
                    return _paxlabelInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PaxLabel item info.
            /// </summary>
            [RepositoryItemInfo("6aad7c8a-967e-4986-98f4-e6f43c2880c2")]
            public virtual RepoItemInfo PaxLabelInfo
            {
                get
                {
                    return _paxlabelInfo;
                }
            }

            /// <summary>
            /// The AdultPaxPlus item.
            /// </summary>
            [RepositoryItem("fee1095f-ef3d-439d-b6a3-0758258e74c3")]
            public virtual Ranorex.ButtonTag AdultPaxPlus
            {
                get
                {
                    return _adultpaxplusInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AdultPaxPlus item info.
            /// </summary>
            [RepositoryItemInfo("fee1095f-ef3d-439d-b6a3-0758258e74c3")]
            public virtual RepoItemInfo AdultPaxPlusInfo
            {
                get
                {
                    return _adultpaxplusInfo;
                }
            }

            /// <summary>
            /// The AdultPaxMinus item.
            /// </summary>
            [RepositoryItem("7a238ce6-9d00-4157-a08d-5376e08af7a2")]
            public virtual Ranorex.ButtonTag AdultPaxMinus
            {
                get
                {
                    return _adultpaxminusInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AdultPaxMinus item info.
            /// </summary>
            [RepositoryItemInfo("7a238ce6-9d00-4157-a08d-5376e08af7a2")]
            public virtual RepoItemInfo AdultPaxMinusInfo
            {
                get
                {
                    return _adultpaxminusInfo;
                }
            }

            /// <summary>
            /// The PaxClose item.
            /// </summary>
            [RepositoryItem("830cc4fb-e2da-44b5-8f01-5abec5afad40")]
            public virtual Ranorex.ATag PaxClose
            {
                get
                {
                    return _paxcloseInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PaxClose item info.
            /// </summary>
            [RepositoryItemInfo("830cc4fb-e2da-44b5-8f01-5abec5afad40")]
            public virtual RepoItemInfo PaxCloseInfo
            {
                get
                {
                    return _paxcloseInfo;
                }
            }

            /// <summary>
            /// The GiSearchBtn item.
            /// </summary>
            [RepositoryItem("b3a2faf9-b485-46b5-ab61-20529ef8a26a")]
            public virtual Ranorex.ButtonTag GiSearchBtn
            {
                get
                {
                    return _gisearchbtnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The GiSearchBtn item info.
            /// </summary>
            [RepositoryItemInfo("b3a2faf9-b485-46b5-ab61-20529ef8a26a")]
            public virtual RepoItemInfo GiSearchBtnInfo
            {
                get
                {
                    return _gisearchbtnInfo;
                }
            }

            /// <summary>
            /// The DbGreyDrIconSunriseIco24 item.
            /// </summary>
            [RepositoryItem("ddf4aef6-2d02-4221-8495-ca9de27990a8")]
            public virtual Ranorex.ITag DbGreyDrIconSunriseIco24
            {
                get
                {
                    return _dbgreydriconsunriseico24Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The DbGreyDrIconSunriseIco24 item info.
            /// </summary>
            [RepositoryItemInfo("ddf4aef6-2d02-4221-8495-ca9de27990a8")]
            public virtual RepoItemInfo DbGreyDrIconSunriseIco24Info
            {
                get
                {
                    return _dbgreydriconsunriseico24Info;
                }
            }

            /// <summary>
            /// The DbGreyDrIconSunIco24 item.
            /// </summary>
            [RepositoryItem("b4306105-411d-443d-9290-e0e7a326526f")]
            public virtual Ranorex.ITag DbGreyDrIconSunIco24
            {
                get
                {
                    return _dbgreydriconsunico24Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The DbGreyDrIconSunIco24 item info.
            /// </summary>
            [RepositoryItemInfo("b4306105-411d-443d-9290-e0e7a326526f")]
            public virtual RepoItemInfo DbGreyDrIconSunIco24Info
            {
                get
                {
                    return _dbgreydriconsunico24Info;
                }
            }

            /// <summary>
            /// The Stops item.
            /// </summary>
            [RepositoryItem("7ff5b8cf-a648-4ccd-ab93-35f5f325ce73")]
            public virtual Ranorex.SpanTag Stops
            {
                get
                {
                    return _stopsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Stops item info.
            /// </summary>
            [RepositoryItemInfo("7ff5b8cf-a648-4ccd-ab93-35f5f325ce73")]
            public virtual RepoItemInfo StopsInfo
            {
                get
                {
                    return _stopsInfo;
                }
            }

            /// <summary>
            /// The Price item.
            /// </summary>
            [RepositoryItem("d6553973-f152-49cb-a981-2fae2a2b3ed9")]
            public virtual Ranorex.SpanTag Price
            {
                get
                {
                    return _priceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Price item info.
            /// </summary>
            [RepositoryItemInfo("d6553973-f152-49cb-a981-2fae2a2b3ed9")]
            public virtual RepoItemInfo PriceInfo
            {
                get
                {
                    return _priceInfo;
                }
            }

            /// <summary>
            /// The FltFareRulesTab item.
            /// </summary>
            [RepositoryItem("78a5cc3c-786f-464e-99a6-8844e0c3c4a1")]
            public virtual Ranorex.ATag FltFareRulesTab
            {
                get
                {
                    return _fltfarerulestabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FltFareRulesTab item info.
            /// </summary>
            [RepositoryItemInfo("78a5cc3c-786f-464e-99a6-8844e0c3c4a1")]
            public virtual RepoItemInfo FltFareRulesTabInfo
            {
                get
                {
                    return _fltfarerulestabInfo;
                }
            }

            /// <summary>
            /// The Adulttitle1 item.
            /// </summary>
            [RepositoryItem("be931ddf-b478-4aa1-af20-a497c4c4d2c0")]
            public virtual Ranorex.SelectTag Adulttitle1
            {
                get
                {
                    return _adulttitle1Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Adulttitle1 item info.
            /// </summary>
            [RepositoryItemInfo("be931ddf-b478-4aa1-af20-a497c4c4d2c0")]
            public virtual RepoItemInfo Adulttitle1Info
            {
                get
                {
                    return _adulttitle1Info;
                }
            }

            /// <summary>
            /// The AdultfirstName1 item.
            /// </summary>
            [RepositoryItem("7cbcc8da-10ee-4a9e-adea-f32678e89022")]
            public virtual Ranorex.InputTag AdultfirstName1
            {
                get
                {
                    return _adultfirstname1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AdultfirstName1 item info.
            /// </summary>
            [RepositoryItemInfo("7cbcc8da-10ee-4a9e-adea-f32678e89022")]
            public virtual RepoItemInfo AdultfirstName1Info
            {
                get
                {
                    return _adultfirstname1Info;
                }
            }

            /// <summary>
            /// The AdultlastName1 item.
            /// </summary>
            [RepositoryItem("f1fbde7c-0771-4314-bf70-04b87d1f7b7d")]
            public virtual Ranorex.InputTag AdultlastName1
            {
                get
                {
                    return _adultlastname1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AdultlastName1 item info.
            /// </summary>
            [RepositoryItemInfo("f1fbde7c-0771-4314-bf70-04b87d1f7b7d")]
            public virtual RepoItemInfo AdultlastName1Info
            {
                get
                {
                    return _adultlastname1Info;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("8242e0ba-024c-4908-87e0-593a0223b0f4")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("8242e0ba-024c-4908-87e0-593a0223b0f4")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Mobile item.
            /// </summary>
            [RepositoryItem("a3d5fdda-f762-4972-a080-c562b72b48e5")]
            public virtual Ranorex.InputTag Mobile
            {
                get
                {
                    return _mobileInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Mobile item info.
            /// </summary>
            [RepositoryItemInfo("a3d5fdda-f762-4972-a080-c562b72b48e5")]
            public virtual RepoItemInfo MobileInfo
            {
                get
                {
                    return _mobileInfo;
                }
            }

            /// <summary>
            /// The ProceedToPayment item.
            /// </summary>
            [RepositoryItem("c9947627-e930-42aa-8e59-65bd6041d1d0")]
            public virtual Ranorex.ButtonTag ProceedToPayment
            {
                get
                {
                    return _proceedtopaymentInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ProceedToPayment item info.
            /// </summary>
            [RepositoryItemInfo("c9947627-e930-42aa-8e59-65bd6041d1d0")]
            public virtual RepoItemInfo ProceedToPaymentInfo
            {
                get
                {
                    return _proceedtopaymentInfo;
                }
            }

            /// <summary>
            /// The NetBanking item.
            /// </summary>
            [RepositoryItem("ce90ca85-39f7-41f9-b80d-e0ac834746e1")]
            public virtual Ranorex.ATag NetBanking
            {
                get
                {
                    return _netbankingInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NetBanking item info.
            /// </summary>
            [RepositoryItemInfo("ce90ca85-39f7-41f9-b80d-e0ac834746e1")]
            public virtual RepoItemInfo NetBankingInfo
            {
                get
                {
                    return _netbankingInfo;
                }
            }

            /// <summary>
            /// The UpiTab item.
            /// </summary>
            [RepositoryItem("f1b7a876-c9ba-478d-812b-b7ca92b1d2c8")]
            public virtual Ranorex.ATag UpiTab
            {
                get
                {
                    return _upitabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The UpiTab item info.
            /// </summary>
            [RepositoryItemInfo("f1b7a876-c9ba-478d-812b-b7ca92b1d2c8")]
            public virtual RepoItemInfo UpiTabInfo
            {
                get
                {
                    return _upitabInfo;
                }
            }

            /// <summary>
            /// The TezTab item.
            /// </summary>
            [RepositoryItem("f60d3afa-272e-40d0-9529-4db81d598524")]
            public virtual Ranorex.ATag TezTab
            {
                get
                {
                    return _teztabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TezTab item info.
            /// </summary>
            [RepositoryItemInfo("f60d3afa-272e-40d0-9529-4db81d598524")]
            public virtual RepoItemInfo TezTabInfo
            {
                get
                {
                    return _teztabInfo;
                }
            }

            /// <summary>
            /// The AmazonPay item.
            /// </summary>
            [RepositoryItem("34646ad6-c4f9-440b-9f7d-70ad87d47bf4")]
            public virtual Ranorex.ATag AmazonPay
            {
                get
                {
                    return _amazonpayInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AmazonPay item info.
            /// </summary>
            [RepositoryItemInfo("34646ad6-c4f9-440b-9f7d-70ad87d47bf4")]
            public virtual RepoItemInfo AmazonPayInfo
            {
                get
                {
                    return _amazonpayInfo;
                }
            }

            /// <summary>
            /// The PayNetbRb item.
            /// </summary>
            [RepositoryItem("b1c09520-65f0-4e59-ab39-a3c98e3fc2b4")]
            public virtual Ranorex.InputTag PayNetbRb
            {
                get
                {
                    return _paynetbrbInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PayNetbRb item info.
            /// </summary>
            [RepositoryItemInfo("b1c09520-65f0-4e59-ab39-a3c98e3fc2b4")]
            public virtual RepoItemInfo PayNetbRbInfo
            {
                get
                {
                    return _paynetbrbInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("03185af2-7a5a-48f4-ab86-436bfc6236a3")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("03185af2-7a5a-48f4-ab86-436bfc6236a3")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The HttpsGoibiboIbcdnComStyleguideIma item.
            /// </summary>
            [RepositoryItem("da65804f-430a-45cd-8221-ece9b4d015a0")]
            public virtual Ranorex.ImgTag HttpsGoibiboIbcdnComStyleguideIma
            {
                get
                {
                    return _httpsgoibiboibcdncomstyleguideimaInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsGoibiboIbcdnComStyleguideIma item info.
            /// </summary>
            [RepositoryItemInfo("da65804f-430a-45cd-8221-ece9b4d015a0")]
            public virtual RepoItemInfo HttpsGoibiboIbcdnComStyleguideImaInfo
            {
                get
                {
                    return _httpsgoibiboibcdncomstyleguideimaInfo;
                }
            }

            /// <summary>
            /// The FlightDetailsFl folder.
            /// </summary>
            [RepositoryFolder("6bc8b0bc-f337-4ae3-b3f8-d9eb186c3b50")]
            public virtual FlightRepoFolders.FlightDetailsFlFolder FlightDetailsFl
            {
                get { return _flightdetailsfl; }
            }

            /// <summary>
            /// The Header folder.
            /// </summary>
            [RepositoryFolder("d566d489-c87b-4135-879a-1171db0c4116")]
            public virtual FlightRepoFolders.HeaderFolder Header
            {
                get { return _header; }
            }

            /// <summary>
            /// The OfferScroll folder.
            /// </summary>
            [RepositoryFolder("580c812d-416a-409b-a829-95829d4e1c24")]
            public virtual FlightRepoFolders.OfferScrollFolder OfferScroll
            {
                get { return _offerscroll; }
            }

            /// <summary>
            /// The NavSectionTabs folder.
            /// </summary>
            [RepositoryFolder("2bdb40a7-a7a9-44fc-8c33-251a4637f6cc")]
            public virtual FlightRepoFolders.NavSectionTabsFolder NavSectionTabs
            {
                get { return _navsectiontabs; }
            }
        }

        /// <summary>
        /// The FlightDetailsFlFolder folder.
        /// </summary>
        [RepositoryFolder("6bc8b0bc-f337-4ae3-b3f8-d9eb186c3b50")]
        public partial class FlightDetailsFlFolder : RepoGenBaseFolder
        {
            RepoItemInfo _baggageandfarerulesInfo;
            RepoItemInfo _javascriptvoid0Info;
            RepoItemInfo _cancellationradioInfo;
            RepoItemInfo _insuranceradioInfo;

            /// <summary>
            /// Creates a new FlightDetailsFl  folder.
            /// </summary>
            public FlightDetailsFlFolder(RepoGenBaseFolder parentFolder) :
                    base("FlightDetailsFl", ".//div[#'content']/div/div[2]/div/div[2]/div/div[1]", parentFolder, 30000, null, false, "6bc8b0bc-f337-4ae3-b3f8-d9eb186c3b50", "")
            {
                _baggageandfarerulesInfo = new RepoItemInfo(this, "BaggageAndFareRules", "div[1]/div[2]//a[@innertext='Baggage and Fare Rules']", 30000, null, "3f50dc65-4756-4240-95f6-a1e7aadf072a");
                _javascriptvoid0Info = new RepoItemInfo(this, "JavascriptVoid0", "div[1]/div[3]//a[@href='javascript:void(0)']", 30000, null, "7881eb6a-49e6-4315-bd5c-bd2a9240b46d");
                _cancellationradioInfo = new RepoItemInfo(this, "CancellationRadio", "div[2]/div[2]/div[1]/div/div/div[1]/div[2]//input[@name='cancellationRadio']", 30000, null, "7ba96f5e-a47f-4aea-a905-82c07e1b4608");
                _insuranceradioInfo = new RepoItemInfo(this, "InsuranceRadio", "div[3]//input[@name='insuranceRadio']", 30000, null, "1d134b13-fec0-4867-8594-b51aecbec055");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6bc8b0bc-f337-4ae3-b3f8-d9eb186c3b50")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6bc8b0bc-f337-4ae3-b3f8-d9eb186c3b50")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BaggageAndFareRules item.
            /// </summary>
            [RepositoryItem("3f50dc65-4756-4240-95f6-a1e7aadf072a")]
            public virtual Ranorex.ATag BaggageAndFareRules
            {
                get
                {
                    return _baggageandfarerulesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BaggageAndFareRules item info.
            /// </summary>
            [RepositoryItemInfo("3f50dc65-4756-4240-95f6-a1e7aadf072a")]
            public virtual RepoItemInfo BaggageAndFareRulesInfo
            {
                get
                {
                    return _baggageandfarerulesInfo;
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item.
            /// </summary>
            [RepositoryItem("7881eb6a-49e6-4315-bd5c-bd2a9240b46d")]
            public virtual Ranorex.ATag JavascriptVoid0
            {
                get
                {
                    return _javascriptvoid0Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item info.
            /// </summary>
            [RepositoryItemInfo("7881eb6a-49e6-4315-bd5c-bd2a9240b46d")]
            public virtual RepoItemInfo JavascriptVoid0Info
            {
                get
                {
                    return _javascriptvoid0Info;
                }
            }

            /// <summary>
            /// The CancellationRadio item.
            /// </summary>
            [RepositoryItem("7ba96f5e-a47f-4aea-a905-82c07e1b4608")]
            public virtual Ranorex.InputTag CancellationRadio
            {
                get
                {
                    return _cancellationradioInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CancellationRadio item info.
            /// </summary>
            [RepositoryItemInfo("7ba96f5e-a47f-4aea-a905-82c07e1b4608")]
            public virtual RepoItemInfo CancellationRadioInfo
            {
                get
                {
                    return _cancellationradioInfo;
                }
            }

            /// <summary>
            /// The InsuranceRadio item.
            /// </summary>
            [RepositoryItem("1d134b13-fec0-4867-8594-b51aecbec055")]
            public virtual Ranorex.InputTag InsuranceRadio
            {
                get
                {
                    return _insuranceradioInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InsuranceRadio item info.
            /// </summary>
            [RepositoryItemInfo("1d134b13-fec0-4867-8594-b51aecbec055")]
            public virtual RepoItemInfo InsuranceRadioInfo
            {
                get
                {
                    return _insuranceradioInfo;
                }
            }
        }

        /// <summary>
        /// The HeaderFolder folder.
        /// </summary>
        [RepositoryFolder("d566d489-c87b-4135-879a-1171db0c4116")]
        public partial class HeaderFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttontagokInfo;
            RepoItemInfo _baggageinformationInfo;
            RepoItemInfo _cancellationrulesInfo;
            RepoItemInfo _faredetailsInfo;
            RepoItemInfo _fliconinfoico11blackInfo;
            RepoItemInfo _flightdetailsInfo;
            RepoItemInfo _fliconclose1ico20Info;
            RepoItemInfo _buttonInfo;

            /// <summary>
            /// Creates a new Header  folder.
            /// </summary>
            public HeaderFolder(RepoGenBaseFolder parentFolder) :
                    base("Header", ".//div[#'content']/div/div[2]/div", parentFolder, 30000, null, false, "d566d489-c87b-4135-879a-1171db0c4116", "")
            {
                _buttontagokInfo = new RepoItemInfo(this, "ButtonTagOK", "div[3]/div[2]/div/div/?/?/button[@innertext='OK']", 30000, null, "b1ae3184-49e1-44df-be7d-41eb6fff85fc");
                _baggageinformationInfo = new RepoItemInfo(this, "BaggageInformation", "div[4]/div/div[4]/div[3]//ul/li[@innertext='Baggage Information']", 30000, null, "59ed581f-4391-4c38-a74e-8a8f15faa059");
                _cancellationrulesInfo = new RepoItemInfo(this, "CancellationRules", "div[4]/div/div[4]/div[3]//ul/li[@innertext='Cancellation Rules']", 30000, null, "c36e20ee-9f8b-44b9-938b-25434669a3cb");
                _faredetailsInfo = new RepoItemInfo(this, "FareDetails", "div[4]/div/div[4]/div[3]//ul/li[@innertext='Fare Details']", 30000, null, "351382bc-c0b3-44c4-a3d5-9b7eb0e9e82b");
                _fliconinfoico11blackInfo = new RepoItemInfo(this, "FlIconInfoIco11Black", "div[4]/div/div[4]/div[3]/div/div[1]/span/span[2]/i", 30000, null, "d0c5b358-c447-45eb-bcd8-51a8a75b8308");
                _flightdetailsInfo = new RepoItemInfo(this, "FlightDetails", "div[4]/div/div[4]/div[3]/div/div[2]/a[@innertext='Flight Details']", 30000, null, "80428207-8a6f-44e0-a043-0501d7887a36");
                _fliconclose1ico20Info = new RepoItemInfo(this, "FlIconClose1Ico20", "div[4]/div/div[4]/div[3]/div[2]/div[1]/span/a[@href='javascript:void(0);']/i", 30000, null, "f8222cba-e5cd-429e-9bb8-b0d5d3833d32");
                _buttonInfo = new RepoItemInfo(this, "Button", "div[4]/div/div[6]/div[2]/div[2]/div/div/span[1]/?/?/input[@type='button']", 30000, null, "55a429e6-aa2c-428b-b772-f749aa11eacc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d566d489-c87b-4135-879a-1171db0c4116")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d566d489-c87b-4135-879a-1171db0c4116")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonTagOK item.
            /// </summary>
            [RepositoryItem("b1ae3184-49e1-44df-be7d-41eb6fff85fc")]
            public virtual Ranorex.ButtonTag ButtonTagOK
            {
                get
                {
                    return _buttontagokInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagOK item info.
            /// </summary>
            [RepositoryItemInfo("b1ae3184-49e1-44df-be7d-41eb6fff85fc")]
            public virtual RepoItemInfo ButtonTagOKInfo
            {
                get
                {
                    return _buttontagokInfo;
                }
            }

            /// <summary>
            /// The BaggageInformation item.
            /// </summary>
            [RepositoryItem("59ed581f-4391-4c38-a74e-8a8f15faa059")]
            public virtual Ranorex.LiTag BaggageInformation
            {
                get
                {
                    return _baggageinformationInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The BaggageInformation item info.
            /// </summary>
            [RepositoryItemInfo("59ed581f-4391-4c38-a74e-8a8f15faa059")]
            public virtual RepoItemInfo BaggageInformationInfo
            {
                get
                {
                    return _baggageinformationInfo;
                }
            }

            /// <summary>
            /// The CancellationRules item.
            /// </summary>
            [RepositoryItem("c36e20ee-9f8b-44b9-938b-25434669a3cb")]
            public virtual Ranorex.LiTag CancellationRules
            {
                get
                {
                    return _cancellationrulesInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The CancellationRules item info.
            /// </summary>
            [RepositoryItemInfo("c36e20ee-9f8b-44b9-938b-25434669a3cb")]
            public virtual RepoItemInfo CancellationRulesInfo
            {
                get
                {
                    return _cancellationrulesInfo;
                }
            }

            /// <summary>
            /// The FareDetails item.
            /// </summary>
            [RepositoryItem("351382bc-c0b3-44c4-a3d5-9b7eb0e9e82b")]
            public virtual Ranorex.LiTag FareDetails
            {
                get
                {
                    return _faredetailsInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The FareDetails item info.
            /// </summary>
            [RepositoryItemInfo("351382bc-c0b3-44c4-a3d5-9b7eb0e9e82b")]
            public virtual RepoItemInfo FareDetailsInfo
            {
                get
                {
                    return _faredetailsInfo;
                }
            }

            /// <summary>
            /// The FlIconInfoIco11Black item.
            /// </summary>
            [RepositoryItem("d0c5b358-c447-45eb-bcd8-51a8a75b8308")]
            public virtual Ranorex.ITag FlIconInfoIco11Black
            {
                get
                {
                    return _fliconinfoico11blackInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FlIconInfoIco11Black item info.
            /// </summary>
            [RepositoryItemInfo("d0c5b358-c447-45eb-bcd8-51a8a75b8308")]
            public virtual RepoItemInfo FlIconInfoIco11BlackInfo
            {
                get
                {
                    return _fliconinfoico11blackInfo;
                }
            }

            /// <summary>
            /// The FlightDetails item.
            /// </summary>
            [RepositoryItem("80428207-8a6f-44e0-a043-0501d7887a36")]
            public virtual Ranorex.ATag FlightDetails
            {
                get
                {
                    return _flightdetailsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FlightDetails item info.
            /// </summary>
            [RepositoryItemInfo("80428207-8a6f-44e0-a043-0501d7887a36")]
            public virtual RepoItemInfo FlightDetailsInfo
            {
                get
                {
                    return _flightdetailsInfo;
                }
            }

            /// <summary>
            /// The FlIconClose1Ico20 item.
            /// </summary>
            [RepositoryItem("f8222cba-e5cd-429e-9bb8-b0d5d3833d32")]
            public virtual Ranorex.ITag FlIconClose1Ico20
            {
                get
                {
                    return _fliconclose1ico20Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FlIconClose1Ico20 item info.
            /// </summary>
            [RepositoryItemInfo("f8222cba-e5cd-429e-9bb8-b0d5d3833d32")]
            public virtual RepoItemInfo FlIconClose1Ico20Info
            {
                get
                {
                    return _fliconclose1ico20Info;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("55a429e6-aa2c-428b-b772-f749aa11eacc")]
            public virtual Ranorex.InputTag Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("55a429e6-aa2c-428b-b772-f749aa11eacc")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }
        }

        /// <summary>
        /// The OfferScrollFolder folder.
        /// </summary>
        [RepositoryFolder("580c812d-416a-409b-a829-95829d4e1c24")]
        public partial class OfferScrollFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iconquestionop07ico14flpadt2padl5Info;
            RepoItemInfo _iconquestionop07ico14flpadt2padl51Info;
            RepoItemInfo _removeInfo;
            RepoItemInfo _controlindicatorvmiddleInfo;
            RepoItemInfo _controlindicatorvmiddle1Info;
            RepoItemInfo _controlindicatorvmiddle2Info;
            RepoItemInfo _controlindicatorvmiddle3Info;

            /// <summary>
            /// Creates a new OfferScroll  folder.
            /// </summary>
            public OfferScrollFolder(RepoGenBaseFolder parentFolder) :
                    base("OfferScroll", ".//div[#'fareSummary']/div[1]", parentFolder, 30000, null, false, "580c812d-416a-409b-a829-95829d4e1c24", "")
            {
                _iconquestionop07ico14flpadt2padl5Info = new RepoItemInfo(this, "IconQuestionOp07Ico14FlPadT2PadL5", "div[1]/div[2]/div[1]/div[2]/span[2]/i", 30000, null, "c571ef8b-a582-48a8-a29c-21cc1a2931de");
                _iconquestionop07ico14flpadt2padl51Info = new RepoItemInfo(this, "IconQuestionOp07Ico14FlPadT2PadL51", "div[1]/div[2]/div[2]/div[2]/span[2]/i", 30000, null, "3d561c4b-5586-47fb-8b46-f911d23a843d");
                _removeInfo = new RepoItemInfo(this, "Remove", "div[2]/div[1]/div[2]/div[1]/div[2]/a[@innertext='Remove']", 30000, null, "4ed14a81-6bc6-490c-8204-76def722f504");
                _controlindicatorvmiddleInfo = new RepoItemInfo(this, "ControlIndicatorVMiddle", "div[2]/div[1]/div[2]/div[3]/span[1]/?/?/div", 30000, null, "edb48a6e-1037-41d6-b8b1-b44f77dd102c");
                _controlindicatorvmiddle1Info = new RepoItemInfo(this, "ControlIndicatorVMiddle1", "div[2]/div[1]/div[2]/div[4]/span[1]/?/?/div", 30000, null, "bc858b66-95fc-4d39-b4f0-12345a37b640");
                _controlindicatorvmiddle2Info = new RepoItemInfo(this, "ControlIndicatorVMiddle2", "div[2]/div[1]/div[2]/div[5]/span[1]/?/?/div", 30000, null, "6c2edf2e-c128-4307-a00f-f69bc36310d6");
                _controlindicatorvmiddle3Info = new RepoItemInfo(this, "ControlIndicatorVMiddle3", "div[2]/div[1]/div[2]/div[6]/span[1]/?/?/div", 30000, null, "ccbf2bc8-ae4f-4214-81b4-14a34d002ca5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("580c812d-416a-409b-a829-95829d4e1c24")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("580c812d-416a-409b-a829-95829d4e1c24")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IconQuestionOp07Ico14FlPadT2PadL5 item.
            /// </summary>
            [RepositoryItem("c571ef8b-a582-48a8-a29c-21cc1a2931de")]
            public virtual Ranorex.ITag IconQuestionOp07Ico14FlPadT2PadL5
            {
                get
                {
                    return _iconquestionop07ico14flpadt2padl5Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IconQuestionOp07Ico14FlPadT2PadL5 item info.
            /// </summary>
            [RepositoryItemInfo("c571ef8b-a582-48a8-a29c-21cc1a2931de")]
            public virtual RepoItemInfo IconQuestionOp07Ico14FlPadT2PadL5Info
            {
                get
                {
                    return _iconquestionop07ico14flpadt2padl5Info;
                }
            }

            /// <summary>
            /// The IconQuestionOp07Ico14FlPadT2PadL51 item.
            /// </summary>
            [RepositoryItem("3d561c4b-5586-47fb-8b46-f911d23a843d")]
            public virtual Ranorex.ITag IconQuestionOp07Ico14FlPadT2PadL51
            {
                get
                {
                    return _iconquestionop07ico14flpadt2padl51Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IconQuestionOp07Ico14FlPadT2PadL51 item info.
            /// </summary>
            [RepositoryItemInfo("3d561c4b-5586-47fb-8b46-f911d23a843d")]
            public virtual RepoItemInfo IconQuestionOp07Ico14FlPadT2PadL51Info
            {
                get
                {
                    return _iconquestionop07ico14flpadt2padl51Info;
                }
            }

            /// <summary>
            /// The Remove item.
            /// </summary>
            [RepositoryItem("4ed14a81-6bc6-490c-8204-76def722f504")]
            public virtual Ranorex.ATag Remove
            {
                get
                {
                    return _removeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Remove item info.
            /// </summary>
            [RepositoryItemInfo("4ed14a81-6bc6-490c-8204-76def722f504")]
            public virtual RepoItemInfo RemoveInfo
            {
                get
                {
                    return _removeInfo;
                }
            }

            /// <summary>
            /// The ControlIndicatorVMiddle item.
            /// </summary>
            [RepositoryItem("edb48a6e-1037-41d6-b8b1-b44f77dd102c")]
            public virtual Ranorex.DivTag ControlIndicatorVMiddle
            {
                get
                {
                    return _controlindicatorvmiddleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ControlIndicatorVMiddle item info.
            /// </summary>
            [RepositoryItemInfo("edb48a6e-1037-41d6-b8b1-b44f77dd102c")]
            public virtual RepoItemInfo ControlIndicatorVMiddleInfo
            {
                get
                {
                    return _controlindicatorvmiddleInfo;
                }
            }

            /// <summary>
            /// The ControlIndicatorVMiddle1 item.
            /// </summary>
            [RepositoryItem("bc858b66-95fc-4d39-b4f0-12345a37b640")]
            public virtual Ranorex.DivTag ControlIndicatorVMiddle1
            {
                get
                {
                    return _controlindicatorvmiddle1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ControlIndicatorVMiddle1 item info.
            /// </summary>
            [RepositoryItemInfo("bc858b66-95fc-4d39-b4f0-12345a37b640")]
            public virtual RepoItemInfo ControlIndicatorVMiddle1Info
            {
                get
                {
                    return _controlindicatorvmiddle1Info;
                }
            }

            /// <summary>
            /// The ControlIndicatorVMiddle2 item.
            /// </summary>
            [RepositoryItem("6c2edf2e-c128-4307-a00f-f69bc36310d6")]
            public virtual Ranorex.DivTag ControlIndicatorVMiddle2
            {
                get
                {
                    return _controlindicatorvmiddle2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ControlIndicatorVMiddle2 item info.
            /// </summary>
            [RepositoryItemInfo("6c2edf2e-c128-4307-a00f-f69bc36310d6")]
            public virtual RepoItemInfo ControlIndicatorVMiddle2Info
            {
                get
                {
                    return _controlindicatorvmiddle2Info;
                }
            }

            /// <summary>
            /// The ControlIndicatorVMiddle3 item.
            /// </summary>
            [RepositoryItem("ccbf2bc8-ae4f-4214-81b4-14a34d002ca5")]
            public virtual Ranorex.DivTag ControlIndicatorVMiddle3
            {
                get
                {
                    return _controlindicatorvmiddle3Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ControlIndicatorVMiddle3 item info.
            /// </summary>
            [RepositoryItemInfo("ccbf2bc8-ae4f-4214-81b4-14a34d002ca5")]
            public virtual RepoItemInfo ControlIndicatorVMiddle3Info
            {
                get
                {
                    return _controlindicatorvmiddle3Info;
                }
            }
        }

        /// <summary>
        /// The NavSectionTabsFolder folder.
        /// </summary>
        [RepositoryFolder("2bdb40a7-a7a9-44fc-8c33-251a4637f6cc")]
        public partial class NavSectionTabsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _resetfiltersInfo;
            RepoItemInfo _labeltag1stopInfo;
            RepoItemInfo _allstopsInfo;
            RepoItemInfo _nonstopInfo;

            /// <summary>
            /// Creates a new NavSectionTabs  folder.
            /// </summary>
            public NavSectionTabsFolder(RepoGenBaseFolder parentFolder) :
                    base("NavSectionTabs", ".//div[#'sticky']/?/?/ul", parentFolder, 30000, null, false, "2bdb40a7-a7a9-44fc-8c33-251a4637f6cc", "")
            {
                _resetfiltersInfo = new RepoItemInfo(this, "ResetFilters", "?/?/a[@innertext='Reset Filters']", 30000, null, "a24bc2c5-14e5-4b0e-a2c5-a81ac38e0c4c");
                _labeltag1stopInfo = new RepoItemInfo(this, "LabelTag1Stop", "li[3]/ul//label[@innertext='1 Stop']", 30000, null, "92c877ff-8272-4aec-87d5-e692a7b40939");
                _allstopsInfo = new RepoItemInfo(this, "AllStops", "li[3]/ul//label[@innertext='All Stops']", 30000, null, "d1b57200-59ae-4ffb-b929-540aefa1bbe8");
                _nonstopInfo = new RepoItemInfo(this, "NonStop", "li[3]/ul//label[@innertext='Non Stop']", 30000, null, "797c5abd-a827-465c-a0d0-fbb0c35e6123");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2bdb40a7-a7a9-44fc-8c33-251a4637f6cc")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2bdb40a7-a7a9-44fc-8c33-251a4637f6cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ResetFilters item.
            /// </summary>
            [RepositoryItem("a24bc2c5-14e5-4b0e-a2c5-a81ac38e0c4c")]
            public virtual Ranorex.ATag ResetFilters
            {
                get
                {
                    return _resetfiltersInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ResetFilters item info.
            /// </summary>
            [RepositoryItemInfo("a24bc2c5-14e5-4b0e-a2c5-a81ac38e0c4c")]
            public virtual RepoItemInfo ResetFiltersInfo
            {
                get
                {
                    return _resetfiltersInfo;
                }
            }

            /// <summary>
            /// The LabelTag1Stop item.
            /// </summary>
            [RepositoryItem("92c877ff-8272-4aec-87d5-e692a7b40939")]
            public virtual Ranorex.LabelTag LabelTag1Stop
            {
                get
                {
                    return _labeltag1stopInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The LabelTag1Stop item info.
            /// </summary>
            [RepositoryItemInfo("92c877ff-8272-4aec-87d5-e692a7b40939")]
            public virtual RepoItemInfo LabelTag1StopInfo
            {
                get
                {
                    return _labeltag1stopInfo;
                }
            }

            /// <summary>
            /// The AllStops item.
            /// </summary>
            [RepositoryItem("d1b57200-59ae-4ffb-b929-540aefa1bbe8")]
            public virtual Ranorex.LabelTag AllStops
            {
                get
                {
                    return _allstopsInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The AllStops item info.
            /// </summary>
            [RepositoryItemInfo("d1b57200-59ae-4ffb-b929-540aefa1bbe8")]
            public virtual RepoItemInfo AllStopsInfo
            {
                get
                {
                    return _allstopsInfo;
                }
            }

            /// <summary>
            /// The NonStop item.
            /// </summary>
            [RepositoryItem("797c5abd-a827-465c-a0d0-fbb0c35e6123")]
            public virtual Ranorex.LabelTag NonStop
            {
                get
                {
                    return _nonstopInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The NonStop item info.
            /// </summary>
            [RepositoryItemInfo("797c5abd-a827-465c-a0d0-fbb0c35e6123")]
            public virtual RepoItemInfo NonStopInfo
            {
                get
                {
                    return _nonstopInfo;
                }
            }
        }

        /// <summary>
        /// The StateBankOfIndiaInternetBankingAppFolder folder.
        /// </summary>
        [RepositoryFolder("4e5f6800-6471-4fca-bb4f-97527b34ee83")]
        public partial class StateBankOfIndiaInternetBankingAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clickhereInfo;

            /// <summary>
            /// Creates a new StateBankOfIndiaInternetBanking  folder.
            /// </summary>
            public StateBankOfIndiaInternetBankingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("StateBankOfIndiaInternetBanking", "/dom[@domain='merchant.onlinesbi.com']", parentFolder, 30000, null, false, "4e5f6800-6471-4fca-bb4f-97527b34ee83", "")
            {
                _clickhereInfo = new RepoItemInfo(this, "ClickHere", ".//div[#'login_block']/div[5]/ul/?/?/a[@innertext='Click here']", 30000, null, "d9520956-039b-4f1d-8aa6-a9bf0f08164e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4e5f6800-6471-4fca-bb4f-97527b34ee83")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4e5f6800-6471-4fca-bb4f-97527b34ee83")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClickHere item.
            /// </summary>
            [RepositoryItem("d9520956-039b-4f1d-8aa6-a9bf0f08164e")]
            public virtual Ranorex.ATag ClickHere
            {
                get
                {
                    return _clickhereInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ClickHere item info.
            /// </summary>
            [RepositoryItemInfo("d9520956-039b-4f1d-8aa6-a9bf0f08164e")]
            public virtual RepoItemInfo ClickHereInfo
            {
                get
                {
                    return _clickhereInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}