///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Goibibo_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The International_flight recording.
    /// </summary>
    [TestModule("1059b405-4c16-42f4-8fdf-294449b58f89", ModuleType.Recording, 1)]
    public partial class International_flight : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Goibibo_TestRepository repository.
        /// </summary>
        public static Goibibo_TestRepository repo = Goibibo_TestRepository.Instance;

        static International_flight instance = new International_flight();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public International_flight()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static International_flight Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.IconFlightsDbBlueIco24Lh12PadT5P' at 13;21.", repo.OnlineFlightBookingHotelsBusAmp1.IconFlightsDbBlueIco24Lh12PadT5PInfo, new RecordItemIndex(0));
            repo.OnlineFlightBookingHotelsBusAmp1.IconFlightsDbBlueIco24Lh12PadT5P.Click("13;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.GosuggestInputSrc' at 88;31.", repo.OnlineFlightBookingHotelsBusAmp1.GosuggestInputSrcInfo, new RecordItemIndex(1));
            repo.OnlineFlightBookingHotelsBusAmp1.GosuggestInputSrc.Click("88;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'de' with focus on 'OnlineFlightBookingHotelsBusAmp1.GosuggestInputSrc'.", repo.OnlineFlightBookingHotelsBusAmp1.GosuggestInputSrcInfo, new RecordItemIndex(2));
            repo.OnlineFlightBookingHotelsBusAmp1.GosuggestInputSrc.PressKeys("de");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.SpanTagDEL' at 6;7.", repo.OnlineFlightBookingHotelsBusAmp1.SpanTagDELInfo, new RecordItemIndex(3));
            repo.OnlineFlightBookingHotelsBusAmp1.SpanTagDEL.Click("6;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.GosuggestInputDest' at 42;17.", repo.OnlineFlightBookingHotelsBusAmp1.GosuggestInputDestInfo, new RecordItemIndex(4));
            repo.OnlineFlightBookingHotelsBusAmp1.GosuggestInputDest.Click("42;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'singa' with focus on 'OnlineFlightBookingHotelsBusAmp1.GosuggestInputDest'.", repo.OnlineFlightBookingHotelsBusAmp1.GosuggestInputDestInfo, new RecordItemIndex(5));
            repo.OnlineFlightBookingHotelsBusAmp1.GosuggestInputDest.PressKeys("singa");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.Singapore' at 43;10.", repo.OnlineFlightBookingHotelsBusAmp1.SingaporeInfo, new RecordItemIndex(6));
            repo.OnlineFlightBookingHotelsBusAmp1.Singapore.Click("43;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Fare20190125' at 11;6.", repo.OnlineFlightBookingHotelsBusAmp.Fare20190125Info, new RecordItemIndex(7));
            repo.OnlineFlightBookingHotelsBusAmp.Fare20190125.Click("11;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'B' on item 'OnlineFlightBookingHotelsBusAmp.GiClass'.", repo.OnlineFlightBookingHotelsBusAmp.GiClassInfo, new RecordItemIndex(8));
            repo.OnlineFlightBookingHotelsBusAmp.GiClass.Element.SetAttributeValue("TagValue", "B");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'E' on item 'OnlineFlightBookingHotelsBusAmp.GiClass'.", repo.OnlineFlightBookingHotelsBusAmp.GiClassInfo, new RecordItemIndex(9));
            repo.OnlineFlightBookingHotelsBusAmp.GiClass.Element.SetAttributeValue("TagValue", "E");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.GiSearchBtn' at 62;11.", repo.OnlineFlightBookingHotelsBusAmp1.GiSearchBtnInfo, new RecordItemIndex(10));
            repo.OnlineFlightBookingHotelsBusAmp1.GiSearchBtn.Click("62;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(11));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(12));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(13));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.IconArrowDownFlDownArrFilter' at 6;1.", repo.OnlineFlightBookingHotelsBusAmp.IconArrowDownFlDownArrFilterInfo, new RecordItemIndex(15));
            repo.OnlineFlightBookingHotelsBusAmp.IconArrowDownFlDownArrFilter.Click("6;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.Time' at 20;1.", repo.OnlineFlightBookingHotelsBusAmp1.TimeInfo, new RecordItemIndex(16));
            repo.OnlineFlightBookingHotelsBusAmp1.Time.Click("20;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.DbGreyDrIconSunriseIco24' at 41;11.", repo.OnlineFlightBookingHotelsBusAmp1.DbGreyDrIconSunriseIco24Info, new RecordItemIndex(17));
            repo.OnlineFlightBookingHotelsBusAmp1.DbGreyDrIconSunriseIco24.Click("41;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.DbGreyDrIconSunIco24' at 36;4.", repo.OnlineFlightBookingHotelsBusAmp1.DbGreyDrIconSunIco24Info, new RecordItemIndex(18));
            repo.OnlineFlightBookingHotelsBusAmp1.DbGreyDrIconSunIco24.Click("36;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.ResetFilters' at 67;0.", repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.ResetFiltersInfo, new RecordItemIndex(19));
            repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.ResetFilters.Click("67;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.Stops' at 31;10.", repo.OnlineFlightBookingHotelsBusAmp1.StopsInfo, new RecordItemIndex(20));
            repo.OnlineFlightBookingHotelsBusAmp1.Stops.Click("31;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.NonStop' at 10;7.", repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.NonStopInfo, new RecordItemIndex(21));
            repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.NonStop.Click("10;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.LabelTag1Stop' at 6;6.", repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.LabelTag1StopInfo, new RecordItemIndex(22));
            repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.LabelTag1Stop.Click("6;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.LabelTag2Stops' at 11;6.", repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.LabelTag2StopsInfo, new RecordItemIndex(23));
            repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.LabelTag2Stops.Click("11;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.AllStops' at 11;1.", repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.AllStopsInfo, new RecordItemIndex(24));
            repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.AllStops.Click("11;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlIconfltAirlinesPadT5Ico12DbXs' at 28;10.", repo.OnlineFlightBookingHotelsBusAmp.FlIconfltAirlinesPadT5Ico12DbXsInfo, new RecordItemIndex(25));
            repo.OnlineFlightBookingHotelsBusAmp.FlIconfltAirlinesPadT5Ico12DbXs.Click("28;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(26));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(27));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.Airports' at 16;7.", repo.OnlineFlightBookingHotelsBusAmp1.AirportsInfo, new RecordItemIndex(28));
            repo.OnlineFlightBookingHotelsBusAmp1.Airports.Click("16;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(29));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(30));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.Airlines' at 24;9.", repo.OnlineFlightBookingHotelsBusAmp1.AirlinesInfo, new RecordItemIndex(31));
            repo.OnlineFlightBookingHotelsBusAmp1.Airlines.Click("24;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.AirIndia' at 6;9.", repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.AirIndiaInfo, new RecordItemIndex(32));
            repo.OnlineFlightBookingHotelsBusAmp1.NavSectionTabs.AirIndia.Click("6;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(33));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(34));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Button' at 33;7.", repo.OnlineFlightBookingHotelsBusAmp.ButtonInfo, new RecordItemIndex(35));
            repo.OnlineFlightBookingHotelsBusAmp.Button.Click("33;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1680 units.", new RecordItemIndex(36));
            Mouse.ScrollWheel(-1680);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(37));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.FlightDetailsFl.BaggageAndFareRules' at 67;13.", repo.OnlineFlightBookingHotelsBusAmp1.FlightDetailsFl.BaggageAndFareRulesInfo, new RecordItemIndex(38));
            repo.OnlineFlightBookingHotelsBusAmp1.FlightDetailsFl.BaggageAndFareRules.Click("67;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.FltFareRulesTab' at 54;9.", repo.OnlineFlightBookingHotelsBusAmp1.FltFareRulesTabInfo, new RecordItemIndex(39));
            repo.OnlineFlightBookingHotelsBusAmp1.FltFareRulesTab.Click("54;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(40));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(41));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.FlightDetailsFl.JavascriptVoid01' at 8;6.", repo.OnlineFlightBookingHotelsBusAmp1.FlightDetailsFl.JavascriptVoid01Info, new RecordItemIndex(42));
            repo.OnlineFlightBookingHotelsBusAmp1.FlightDetailsFl.JavascriptVoid01.Click("8;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.FarebreakupTooltipBaseFare' at 257;37.", repo.OnlineFlightBookingHotelsBusAmp1.FarebreakupTooltipBaseFareInfo, new RecordItemIndex(43));
            repo.OnlineFlightBookingHotelsBusAmp1.FarebreakupTooltipBaseFare.Click("257;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.BorderAllPosRelWhiteBgCrdShdwBrRadiu1.IconQuestionOp07Ico14FlPadT2PadL51' at 11;8.", repo.OnlineFlightBookingHotelsBusAmp1.BorderAllPosRelWhiteBgCrdShdwBrRadiu1.IconQuestionOp07Ico14FlPadT2PadL51Info, new RecordItemIndex(44));
            repo.OnlineFlightBookingHotelsBusAmp1.BorderAllPosRelWhiteBgCrdShdwBrRadiu1.IconQuestionOp07Ico14FlPadT2PadL51.Click("11;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(45));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadio' at 8;7.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadioInfo, new RecordItemIndex(46));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadio.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadio' at 8;7.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadioInfo, new RecordItemIndex(47));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.InsuranceRadio.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(48));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '1' on item 'OnlineFlightBookingHotelsBusAmp1.Adulttitle1'.", repo.OnlineFlightBookingHotelsBusAmp1.Adulttitle1Info, new RecordItemIndex(49));
            repo.OnlineFlightBookingHotelsBusAmp1.Adulttitle1.Element.SetAttributeValue("TagValue", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.AdultfirstName1' at 37;12.", repo.OnlineFlightBookingHotelsBusAmp1.AdultfirstName1Info, new RecordItemIndex(50));
            repo.OnlineFlightBookingHotelsBusAmp1.AdultfirstName1.Click("37;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Devendra' with focus on 'OnlineFlightBookingHotelsBusAmp1.AdultfirstName1'.", repo.OnlineFlightBookingHotelsBusAmp1.AdultfirstName1Info, new RecordItemIndex(51));
            repo.OnlineFlightBookingHotelsBusAmp1.AdultfirstName1.PressKeys("Devendra");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.AdultlastName1' at 55;13.", repo.OnlineFlightBookingHotelsBusAmp1.AdultlastName1Info, new RecordItemIndex(52));
            repo.OnlineFlightBookingHotelsBusAmp1.AdultlastName1.Click("55;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Gupta' with focus on 'OnlineFlightBookingHotelsBusAmp1.AdultlastName1'.", repo.OnlineFlightBookingHotelsBusAmp1.AdultlastName1Info, new RecordItemIndex(53));
            repo.OnlineFlightBookingHotelsBusAmp1.AdultlastName1.PressKeys("Gupta");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag' at 464;1229.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTagInfo, new RecordItemIndex(54));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Click("464;1229");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com'.", new RecordItemIndex(55));
            Keyboard.Press("testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.Mobile' at 143;10.", repo.OnlineFlightBookingHotelsBusAmp1.MobileInfo, new RecordItemIndex(56));
            repo.OnlineFlightBookingHotelsBusAmp1.Mobile.Click("143;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9999999999' with focus on 'OnlineFlightBookingHotelsBusAmp1.Mobile'.", repo.OnlineFlightBookingHotelsBusAmp1.MobileInfo, new RecordItemIndex(57));
            repo.OnlineFlightBookingHotelsBusAmp1.Mobile.PressKeys("9999999999");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.IconInfoOp07Ico14PadT2PadL5BlueLt' at 13;7.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.IconInfoOp07Ico14PadT2PadL5BlueLtInfo, new RecordItemIndex(58));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.IconInfoOp07Ico14PadT2PadL5BlueLt.Click("13;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.ButtonTagOK' at 14;5.", repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.ButtonTagOKInfo, new RecordItemIndex(59));
            repo.OnlineFlightBookingHotelsBusAmp.FlightDetailsFl.ButtonTagOK.Click("14;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(60));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.FlightDetailsFl.ProceedToPayment' at 95;22.", repo.OnlineFlightBookingHotelsBusAmp1.FlightDetailsFl.ProceedToPaymentInfo, new RecordItemIndex(61));
            repo.OnlineFlightBookingHotelsBusAmp1.FlightDetailsFl.ProceedToPayment.Click("95;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1080 units.", new RecordItemIndex(62));
            Mouse.ScrollWheel(-1080);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(63));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(64));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(65));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -960 units.", new RecordItemIndex(66));
            Mouse.ScrollWheel(-960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(67));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -960 units.", new RecordItemIndex(68));
            Mouse.ScrollWheel(-960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(69));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -840 units.", new RecordItemIndex(70));
            Mouse.ScrollWheel(-840);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(71));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(72));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.UpiTab' at 36;4.", repo.OnlineFlightBookingHotelsBusAmp1.UpiTabInfo, new RecordItemIndex(73));
            repo.OnlineFlightBookingHotelsBusAmp1.UpiTab.Click("36;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NetBanking' at 44;22.", repo.OnlineFlightBookingHotelsBusAmp.NetBankingInfo, new RecordItemIndex(74));
            repo.OnlineFlightBookingHotelsBusAmp.NetBanking.Click("44;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.PayNetbRb' at 9;1.", repo.OnlineFlightBookingHotelsBusAmp.PayNetbRbInfo, new RecordItemIndex(75));
            repo.OnlineFlightBookingHotelsBusAmp.PayNetbRb.Click("9;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Submit' at 160;23.", repo.OnlineFlightBookingHotelsBusAmp.SubmitInfo, new RecordItemIndex(76));
            repo.OnlineFlightBookingHotelsBusAmp.Submit.Click("160;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(77));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 600 units.", new RecordItemIndex(78));
            Mouse.ScrollWheel(600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(79));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StateBankOfIndiaInternetBanking.ClickHere' at 21;8.", repo.StateBankOfIndiaInternetBanking.ClickHereInfo, new RecordItemIndex(80));
            repo.StateBankOfIndiaInternetBanking.ClickHere.Click("21;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp1.HttpsGoibiboIbcdnComStyleguideIma' at 63;17.", repo.OnlineFlightBookingHotelsBusAmp1.HttpsGoibiboIbcdnComStyleguideImaInfo, new RecordItemIndex(81));
            repo.OnlineFlightBookingHotelsBusAmp1.HttpsGoibiboIbcdnComStyleguideIma.Click("63;17");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
