///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Goibibo_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Sign_IN recording.
    /// </summary>
    [TestModule("3d3c07fc-93f6-49ce-aa8f-8a3d8842f484", ModuleType.Recording, 1)]
    public partial class Sign_IN : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Goibibo_TestRepository repository.
        /// </summary>
        public static Goibibo_TestRepository repo = Goibibo_TestRepository.Instance;

        static Sign_IN instance = new Sign_IN();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Sign_IN()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Sign_IN Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.Goibibo.com\r\n' with browser 'Chrome' in normal mode .", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://www.Goibibo.com\r\n", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma' at 44;10.", repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideImaInfo, new RecordItemIndex(1));
            repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma.Click("44;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GetSignIn' at 15;12.", repo.OnlineFlightBookingHotelsBusAmp.GetSignInInfo, new RecordItemIndex(2));
            repo.OnlineFlightBookingHotelsBusAmp.GetSignIn.Click("15;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Authiframe.AuthMobile' at 79;14.", repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthMobileInfo, new RecordItemIndex(3));
            repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthMobile.Click("79;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '8858558819' with focus on 'OnlineFlightBookingHotelsBusAmp.Authiframe.AuthMobile'.", repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthMobileInfo, new RecordItemIndex(4));
            repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthMobile.PressKeys("8858558819");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Authiframe.MobileSubmitBtn' at 167;40.", repo.OnlineFlightBookingHotelsBusAmp.Authiframe.MobileSubmitBtnInfo, new RecordItemIndex(5));
            repo.OnlineFlightBookingHotelsBusAmp.Authiframe.MobileSubmitBtn.Click("167;40");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Authiframe.AuthCredentialPassword' at 112;34.", repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthCredentialPasswordInfo, new RecordItemIndex(6));
            repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthCredentialPassword.Click("112;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '8858558819' with focus on 'OnlineFlightBookingHotelsBusAmp.Authiframe.AuthCredentialPassword'.", repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthCredentialPasswordInfo, new RecordItemIndex(7));
            repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthCredentialPassword.PressKeys("8858558819");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Authiframe.PasswordEyeMobilePassword' at 9;6.", repo.OnlineFlightBookingHotelsBusAmp.Authiframe.PasswordEyeMobilePasswordInfo, new RecordItemIndex(8));
            repo.OnlineFlightBookingHotelsBusAmp.Authiframe.PasswordEyeMobilePassword.Click("9;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Authiframe.AuthCredentialPasswordSignInBtn' at 150;17.", repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthCredentialPasswordSignInBtnInfo, new RecordItemIndex(9));
            repo.OnlineFlightBookingHotelsBusAmp.Authiframe.AuthCredentialPasswordSignInBtn.Click("150;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma' at 35;15.", repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideImaInfo, new RecordItemIndex(10));
            repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma.Click("35;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
