///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Goibibo_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Train element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("3249f017-dded-4a3e-87ae-23e677f5d192")]
    public partial class Train : RepoGenBaseFolder
    {
        static Train instance = new Train();
        TrainFolders.OnlineFlightBookingHotelsBusAmpAppFolder _onlineflightbookinghotelsbusamp;
        TrainFolders.StateBankOfIndiaInternetBankingAppFolder _statebankofindiainternetbanking;

        /// <summary>
        /// Gets the singleton class instance representing the Train element repository.
        /// </summary>
        [RepositoryFolder("3249f017-dded-4a3e-87ae-23e677f5d192")]
        public static Train Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Train() 
            : base("Train", "/", null, 0, false, "3249f017-dded-4a3e-87ae-23e677f5d192", ".\\RepositoryImages\\Train3249f017.rximgres")
        {
            _onlineflightbookinghotelsbusamp = new TrainFolders.OnlineFlightBookingHotelsBusAmpAppFolder(this);
            _statebankofindiainternetbanking = new TrainFolders.StateBankOfIndiaInternetBankingAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3249f017-dded-4a3e-87ae-23e677f5d192")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The OnlineFlightBookingHotelsBusAmp folder.
        /// </summary>
        [RepositoryFolder("3399e0bb-8795-43b0-9232-712221123d4b")]
        public virtual TrainFolders.OnlineFlightBookingHotelsBusAmpAppFolder OnlineFlightBookingHotelsBusAmp
        {
            get { return _onlineflightbookinghotelsbusamp; }
        }

        /// <summary>
        /// The StateBankOfIndiaInternetBanking folder.
        /// </summary>
        [RepositoryFolder("0e02063f-5773-4a5b-8698-a770b37dbca7")]
        public virtual TrainFolders.StateBankOfIndiaInternetBankingAppFolder StateBankOfIndiaInternetBanking
        {
            get { return _statebankofindiainternetbanking; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class TrainFolders
    {
        /// <summary>
        /// The OnlineFlightBookingHotelsBusAmpAppFolder folder.
        /// </summary>
        [RepositoryFolder("3399e0bb-8795-43b0-9232-712221123d4b")]
        public partial class OnlineFlightBookingHotelsBusAmpAppFolder : RepoGenBaseFolder
        {
            TrainFolders.GiSearchFolder _gisearch;
            TrainFolders.SomeDivTagFolder _somedivtag;
            RepoItemInfo _icontrainfrontviewdbblueico24lh1Info;
            RepoItemInfo _gosuggestinputlInfo;
            RepoItemInfo _maintxtInfo;
            RepoItemInfo _gisearchbtnInfo;
            RepoItemInfo _buttontagyesInfo;
            RepoItemInfo _netbankingInfo;
            RepoItemInfo _paynetbrbInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _httpsgoibiboibcdncomstyleguideimaInfo;

            /// <summary>
            /// Creates a new OnlineFlightBookingHotelsBusAmp  folder.
            /// </summary>
            public OnlineFlightBookingHotelsBusAmpAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OnlineFlightBookingHotelsBusAmp", "/dom[@domain='www.goibibo.com']", parentFolder, 30000, null, false, "3399e0bb-8795-43b0-9232-712221123d4b", "")
            {
                _gisearch = new TrainFolders.GiSearchFolder(this);
                _somedivtag = new TrainFolders.SomeDivTagFolder(this);
                _icontrainfrontviewdbblueico24lh1Info = new RepoItemInfo(this, "IconTrainFrontViewDbBlueIco24Lh1", ".//div[#'header']/div[1]/ul/?/?/a[@href~'^https://www\\.goibibo\\.com/t']/i", 30000, null, "fada0215-c0de-4318-b936-82d59a7a0d27");
                _gosuggestinputlInfo = new RepoItemInfo(this, "GosuggestInputL", ".//input[#'gosuggest_inputL']", 30000, null, "7be13c90-1e73-435d-9332-b68ac6e56d60");
                _maintxtInfo = new RepoItemInfo(this, "MainTxt", ".//li[#'react-autosuggest-1-suggestion--0']/div/div[1]/div", 30000, null, "e4d7d183-25ff-4ee3-9e4f-6cd963c50edf");
                _gisearchbtnInfo = new RepoItemInfo(this, "GiSearchBtn", ".//input[#'gi_search_btn']", 30000, null, "6c9fe03e-0bdc-4314-821e-01a2c92afc25");
                _buttontagyesInfo = new RepoItemInfo(this, "ButtonTagYes", ".//div[#'irctcPop']/div/div/div/?/?/button[@innertext='Yes']", 30000, null, "1993e3d2-13ed-448a-bd1e-4c388068464b");
                _netbankingInfo = new RepoItemInfo(this, "NetBanking", ".//ul[#'tabnav_opts']/?/?/a[@innertext='Net Banking']", 30000, null, "906e5b5d-a0ba-42b7-8cb4-b64a977c6f17");
                _paynetbrbInfo = new RepoItemInfo(this, "PayNetbRb", ".//div[#'netBank']/div[2]/div[6]/?/?/input[@name='pay_netb_rb']", 30000, null, "bb9095e7-dfd1-4ab7-a8f1-2e4f8f2bc6f3");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'netBank']/div[3]/div[4]/?/?/input[@type='submit']", 30000, null, "ad6032aa-3d5d-4961-8f5c-defa61c18a00");
                _httpsgoibiboibcdncomstyleguideimaInfo = new RepoItemInfo(this, "HttpsGoibiboIbcdnComStyleguideIma", ".//div[#'header']//img[@src='https://goibibo.ibcdn.com/styleguide/images/goLogo.png']", 30000, null, "6f73598a-11e0-4186-865a-5b0e7f30b341");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3399e0bb-8795-43b0-9232-712221123d4b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3399e0bb-8795-43b0-9232-712221123d4b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IconTrainFrontViewDbBlueIco24Lh1 item.
            /// </summary>
            [RepositoryItem("fada0215-c0de-4318-b936-82d59a7a0d27")]
            public virtual Ranorex.ITag IconTrainFrontViewDbBlueIco24Lh1
            {
                get
                {
                    return _icontrainfrontviewdbblueico24lh1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IconTrainFrontViewDbBlueIco24Lh1 item info.
            /// </summary>
            [RepositoryItemInfo("fada0215-c0de-4318-b936-82d59a7a0d27")]
            public virtual RepoItemInfo IconTrainFrontViewDbBlueIco24Lh1Info
            {
                get
                {
                    return _icontrainfrontviewdbblueico24lh1Info;
                }
            }

            /// <summary>
            /// The GosuggestInputL item.
            /// </summary>
            [RepositoryItem("7be13c90-1e73-435d-9332-b68ac6e56d60")]
            public virtual Ranorex.InputTag GosuggestInputL
            {
                get
                {
                    return _gosuggestinputlInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GosuggestInputL item info.
            /// </summary>
            [RepositoryItemInfo("7be13c90-1e73-435d-9332-b68ac6e56d60")]
            public virtual RepoItemInfo GosuggestInputLInfo
            {
                get
                {
                    return _gosuggestinputlInfo;
                }
            }

            /// <summary>
            /// The MainTxt item.
            /// </summary>
            [RepositoryItem("e4d7d183-25ff-4ee3-9e4f-6cd963c50edf")]
            public virtual Ranorex.DivTag MainTxt
            {
                get
                {
                    return _maintxtInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MainTxt item info.
            /// </summary>
            [RepositoryItemInfo("e4d7d183-25ff-4ee3-9e4f-6cd963c50edf")]
            public virtual RepoItemInfo MainTxtInfo
            {
                get
                {
                    return _maintxtInfo;
                }
            }

            /// <summary>
            /// The GiSearchBtn item.
            /// </summary>
            [RepositoryItem("6c9fe03e-0bdc-4314-821e-01a2c92afc25")]
            public virtual Ranorex.InputTag GiSearchBtn
            {
                get
                {
                    return _gisearchbtnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GiSearchBtn item info.
            /// </summary>
            [RepositoryItemInfo("6c9fe03e-0bdc-4314-821e-01a2c92afc25")]
            public virtual RepoItemInfo GiSearchBtnInfo
            {
                get
                {
                    return _gisearchbtnInfo;
                }
            }

            /// <summary>
            /// The ButtonTagYes item.
            /// </summary>
            [RepositoryItem("1993e3d2-13ed-448a-bd1e-4c388068464b")]
            public virtual Ranorex.ButtonTag ButtonTagYes
            {
                get
                {
                    return _buttontagyesInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagYes item info.
            /// </summary>
            [RepositoryItemInfo("1993e3d2-13ed-448a-bd1e-4c388068464b")]
            public virtual RepoItemInfo ButtonTagYesInfo
            {
                get
                {
                    return _buttontagyesInfo;
                }
            }

            /// <summary>
            /// The NetBanking item.
            /// </summary>
            [RepositoryItem("906e5b5d-a0ba-42b7-8cb4-b64a977c6f17")]
            public virtual Ranorex.ATag NetBanking
            {
                get
                {
                    return _netbankingInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NetBanking item info.
            /// </summary>
            [RepositoryItemInfo("906e5b5d-a0ba-42b7-8cb4-b64a977c6f17")]
            public virtual RepoItemInfo NetBankingInfo
            {
                get
                {
                    return _netbankingInfo;
                }
            }

            /// <summary>
            /// The PayNetbRb item.
            /// </summary>
            [RepositoryItem("bb9095e7-dfd1-4ab7-a8f1-2e4f8f2bc6f3")]
            public virtual Ranorex.InputTag PayNetbRb
            {
                get
                {
                    return _paynetbrbInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PayNetbRb item info.
            /// </summary>
            [RepositoryItemInfo("bb9095e7-dfd1-4ab7-a8f1-2e4f8f2bc6f3")]
            public virtual RepoItemInfo PayNetbRbInfo
            {
                get
                {
                    return _paynetbrbInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("ad6032aa-3d5d-4961-8f5c-defa61c18a00")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("ad6032aa-3d5d-4961-8f5c-defa61c18a00")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The HttpsGoibiboIbcdnComStyleguideIma item.
            /// </summary>
            [RepositoryItem("6f73598a-11e0-4186-865a-5b0e7f30b341")]
            public virtual Ranorex.ImgTag HttpsGoibiboIbcdnComStyleguideIma
            {
                get
                {
                    return _httpsgoibiboibcdncomstyleguideimaInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsGoibiboIbcdnComStyleguideIma item info.
            /// </summary>
            [RepositoryItemInfo("6f73598a-11e0-4186-865a-5b0e7f30b341")]
            public virtual RepoItemInfo HttpsGoibiboIbcdnComStyleguideImaInfo
            {
                get
                {
                    return _httpsgoibiboibcdncomstyleguideimaInfo;
                }
            }

            /// <summary>
            /// The GiSearch folder.
            /// </summary>
            [RepositoryFolder("657fed3b-da4d-4f8f-9a97-b3e8fb8944fd")]
            public virtual TrainFolders.GiSearchFolder GiSearch
            {
                get { return _gisearch; }
            }

            /// <summary>
            /// The SomeDivTag folder.
            /// </summary>
            [RepositoryFolder("2744e1c5-b665-4671-907d-80532401cd72")]
            public virtual TrainFolders.SomeDivTagFolder SomeDivTag
            {
                get { return _somedivtag; }
            }
        }

        /// <summary>
        /// The GiSearchFolder folder.
        /// </summary>
        [RepositoryFolder("657fed3b-da4d-4f8f-9a97-b3e8fb8944fd")]
        public partial class GiSearchFolder : RepoGenBaseFolder
        {
            RepoItemInfo _gosuggestinputl1Info;
            RepoItemInfo _textInfo;
            RepoItemInfo _daypickernavbuttondaypickernavbuttonInfo;
            RepoItemInfo _divtag17Info;

            /// <summary>
            /// Creates a new GiSearch  folder.
            /// </summary>
            public GiSearchFolder(RepoGenBaseFolder parentFolder) :
                    base("GiSearch", ".//form[#'gi_search']", parentFolder, 30000, null, false, "657fed3b-da4d-4f8f-9a97-b3e8fb8944fd", "")
            {
                _gosuggestinputl1Info = new RepoItemInfo(this, "GosuggestInputL1", ".//input[@type='text' and @value='Kalyan Junction']", 30000, null, "8d9f0bdd-a507-458f-91b7-8003cb87f1f6");
                _textInfo = new RepoItemInfo(this, "Text", "div/div[3]/div[1]//input[@type='text']", 30000, null, "a9493149-62d4-4def-85e4-d7e1412f5d7d");
                _daypickernavbuttondaypickernavbuttonInfo = new RepoItemInfo(this, "DayPickerNavButtonDayPickerNavButton", "div/div[3]/div[1]/div/div/div/div[1]/span[2]", 30000, null, "231b56a5-beac-462c-8b88-0b3a969e66f8");
                _divtag17Info = new RepoItemInfo(this, "DivTag17", "div/div[3]/div[1]/div/div/div/div[2]/div[3]/div[3]/div[@innertext='17']", 30000, null, "954a23ab-11e5-4794-9058-b3f2c03e52a6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("657fed3b-da4d-4f8f-9a97-b3e8fb8944fd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("657fed3b-da4d-4f8f-9a97-b3e8fb8944fd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GosuggestInputL1 item.
            /// </summary>
            [RepositoryItem("8d9f0bdd-a507-458f-91b7-8003cb87f1f6")]
            public virtual Ranorex.InputTag GosuggestInputL1
            {
                get
                {
                    return _gosuggestinputl1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GosuggestInputL1 item info.
            /// </summary>
            [RepositoryItemInfo("8d9f0bdd-a507-458f-91b7-8003cb87f1f6")]
            public virtual RepoItemInfo GosuggestInputL1Info
            {
                get
                {
                    return _gosuggestinputl1Info;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("a9493149-62d4-4def-85e4-d7e1412f5d7d")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("a9493149-62d4-4def-85e4-d7e1412f5d7d")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The DayPickerNavButtonDayPickerNavButton item.
            /// </summary>
            [RepositoryItem("231b56a5-beac-462c-8b88-0b3a969e66f8")]
            public virtual Ranorex.SpanTag DayPickerNavButtonDayPickerNavButton
            {
                get
                {
                    return _daypickernavbuttondaypickernavbuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The DayPickerNavButtonDayPickerNavButton item info.
            /// </summary>
            [RepositoryItemInfo("231b56a5-beac-462c-8b88-0b3a969e66f8")]
            public virtual RepoItemInfo DayPickerNavButtonDayPickerNavButtonInfo
            {
                get
                {
                    return _daypickernavbuttondaypickernavbuttonInfo;
                }
            }

            /// <summary>
            /// The DivTag17 item.
            /// </summary>
            [RepositoryItem("954a23ab-11e5-4794-9058-b3f2c03e52a6")]
            public virtual Ranorex.DivTag DivTag17
            {
                get
                {
                    return _divtag17Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTag17 item info.
            /// </summary>
            [RepositoryItemInfo("954a23ab-11e5-4794-9058-b3f2c03e52a6")]
            public virtual RepoItemInfo DivTag17Info
            {
                get
                {
                    return _divtag17Info;
                }
            }
        }

        /// <summary>
        /// The SomeDivTagFolder folder.
        /// </summary>
        [RepositoryFolder("2744e1c5-b665-4671-907d-80532401cd72")]
        public partial class SomeDivTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _bookagainInfo;
            RepoItemInfo _numberInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _formcontrolinputmediumInfo;
            RepoItemInfo _text2Info;
            RepoItemInfo _text3Info;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _spantagfarebreakupInfo;
            RepoItemInfo _button1Info;
            RepoItemInfo _friconclosefont12ltpopcloseInfo;
            RepoItemInfo _booknowInfo;
            RepoItemInfo _checkavailabilityInfo;
            RepoItemInfo _litag3aInfo;

            /// <summary>
            /// Creates a new SomeDivTag  folder.
            /// </summary>
            public SomeDivTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeDivTag", "body/div[1]/div", parentFolder, 30000, null, false, "2744e1c5-b665-4671-907d-80532401cd72", "")
            {
                _bookagainInfo = new RepoItemInfo(this, "BookAgain", "div[1]/section/section//span[@innertext='Book Again']", 30000, null, "b2a4cd7a-6824-44a8-a6cc-2bcb112e4274");
                _numberInfo = new RepoItemInfo(this, "Number", "div[2]//form[@action='https://www.goibibo.com/trains/booking']/div[1]/div[2]//input[@type='number']", 30000, null, "95f50351-6189-4de0-92aa-ee56233ab382");
                _text1Info = new RepoItemInfo(this, "Text1", "div[2]//form[@action='https://www.goibibo.com/trains/booking']/div[1]/div[2]//input[@type='text']", 30000, null, "82c3f5fd-8a51-435f-bf08-2f3b38018ca3");
                _formcontrolinputmediumInfo = new RepoItemInfo(this, "FormControlInputMedium", "div[2]//form[@action='https://www.goibibo.com/trains/booking']/div[1]/div[2]//select", 30000, null, "a0d5f4e3-a601-4c3f-acc4-7bad51f35a1d");
                _text2Info = new RepoItemInfo(this, "Text2", "div[2]//form[@action='https://www.goibibo.com/trains/booking']/div[7]/div[2]//input[@type='text']", 30000, null, "a64272ee-e6c2-47b8-828c-2e9a97c2da70");
                _text3Info = new RepoItemInfo(this, "Text3", "div[2]//form[@action='https://www.goibibo.com/trains/booking']/div[7]/div[3]//input[@type='text']", 30000, null, "42e8728a-f814-4576-a439-b22346596f3a");
                _buttonInfo = new RepoItemInfo(this, "Button", "div[2]//form[@action='https://www.goibibo.com/trains/booking']/div[8]/?/?/input[@type='button']", 30000, null, "95aa5d36-1d5a-46ca-8ad9-5f51a4d96770");
                _spantagfarebreakupInfo = new RepoItemInfo(this, "SpanTagFareBreakup", "div[2]/div/div[2]/div[3]//span[@innertext=' Fare Breakup']", 30000, null, "7fa3990e-1260-4caa-9df2-44d3f2401cc5");
                _button1Info = new RepoItemInfo(this, "Button1", "div[2]/div/div[2]/div[3]/?/?/input[@type='button']", 30000, null, "583b418e-fb93-4cec-b977-01a137f9ab39");
                _friconclosefont12ltpopcloseInfo = new RepoItemInfo(this, "FrIconCloseFont12LtPopClose", "div[2]/div/div[2]/div[3]/div[3]//a", 30000, null, "5f892ae8-9dac-4855-9383-5afec97303a4");
                _booknowInfo = new RepoItemInfo(this, "BOOKNOW", "div[2]/div[3]/section//button[@innertext='BOOK NOW']", 30000, null, "7832ebf3-e200-4a87-8cf5-b578a815b3e4");
                _checkavailabilityInfo = new RepoItemInfo(this, "CheckAvailability", "div[2]/div[3]/section//span[@innertext='Check Availability']", 30000, null, "8ece57fd-5e54-4e67-8bed-b42cfe03b7d0");
                _litag3aInfo = new RepoItemInfo(this, "LiTag3A", "div[2]/div[3]/section//ul/li[@innertext='3A']", 30000, null, "2900c749-c475-437c-8dde-47f6cd9eec66");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2744e1c5-b665-4671-907d-80532401cd72")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2744e1c5-b665-4671-907d-80532401cd72")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BookAgain item.
            /// </summary>
            [RepositoryItem("b2a4cd7a-6824-44a8-a6cc-2bcb112e4274")]
            public virtual Ranorex.SpanTag BookAgain
            {
                get
                {
                    return _bookagainInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BookAgain item info.
            /// </summary>
            [RepositoryItemInfo("b2a4cd7a-6824-44a8-a6cc-2bcb112e4274")]
            public virtual RepoItemInfo BookAgainInfo
            {
                get
                {
                    return _bookagainInfo;
                }
            }

            /// <summary>
            /// The Number item.
            /// </summary>
            [RepositoryItem("95f50351-6189-4de0-92aa-ee56233ab382")]
            public virtual Ranorex.InputTag Number
            {
                get
                {
                    return _numberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Number item info.
            /// </summary>
            [RepositoryItemInfo("95f50351-6189-4de0-92aa-ee56233ab382")]
            public virtual RepoItemInfo NumberInfo
            {
                get
                {
                    return _numberInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("82c3f5fd-8a51-435f-bf08-2f3b38018ca3")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("82c3f5fd-8a51-435f-bf08-2f3b38018ca3")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The FormControlInputMedium item.
            /// </summary>
            [RepositoryItem("a0d5f4e3-a601-4c3f-acc4-7bad51f35a1d")]
            public virtual Ranorex.SelectTag FormControlInputMedium
            {
                get
                {
                    return _formcontrolinputmediumInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FormControlInputMedium item info.
            /// </summary>
            [RepositoryItemInfo("a0d5f4e3-a601-4c3f-acc4-7bad51f35a1d")]
            public virtual RepoItemInfo FormControlInputMediumInfo
            {
                get
                {
                    return _formcontrolinputmediumInfo;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("a64272ee-e6c2-47b8-828c-2e9a97c2da70")]
            public virtual Ranorex.InputTag Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("a64272ee-e6c2-47b8-828c-2e9a97c2da70")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The Text3 item.
            /// </summary>
            [RepositoryItem("42e8728a-f814-4576-a439-b22346596f3a")]
            public virtual Ranorex.InputTag Text3
            {
                get
                {
                    return _text3Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text3 item info.
            /// </summary>
            [RepositoryItemInfo("42e8728a-f814-4576-a439-b22346596f3a")]
            public virtual RepoItemInfo Text3Info
            {
                get
                {
                    return _text3Info;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("95aa5d36-1d5a-46ca-8ad9-5f51a4d96770")]
            public virtual Ranorex.InputTag Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("95aa5d36-1d5a-46ca-8ad9-5f51a4d96770")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The SpanTagFareBreakup item.
            /// </summary>
            [RepositoryItem("7fa3990e-1260-4caa-9df2-44d3f2401cc5")]
            public virtual Ranorex.SpanTag SpanTagFareBreakup
            {
                get
                {
                    return _spantagfarebreakupInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagFareBreakup item info.
            /// </summary>
            [RepositoryItemInfo("7fa3990e-1260-4caa-9df2-44d3f2401cc5")]
            public virtual RepoItemInfo SpanTagFareBreakupInfo
            {
                get
                {
                    return _spantagfarebreakupInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("583b418e-fb93-4cec-b977-01a137f9ab39")]
            public virtual Ranorex.InputTag Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("583b418e-fb93-4cec-b977-01a137f9ab39")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The FrIconCloseFont12LtPopClose item.
            /// </summary>
            [RepositoryItem("5f892ae8-9dac-4855-9383-5afec97303a4")]
            public virtual Ranorex.ATag FrIconCloseFont12LtPopClose
            {
                get
                {
                    return _friconclosefont12ltpopcloseInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FrIconCloseFont12LtPopClose item info.
            /// </summary>
            [RepositoryItemInfo("5f892ae8-9dac-4855-9383-5afec97303a4")]
            public virtual RepoItemInfo FrIconCloseFont12LtPopCloseInfo
            {
                get
                {
                    return _friconclosefont12ltpopcloseInfo;
                }
            }

            /// <summary>
            /// The BOOKNOW item.
            /// </summary>
            [RepositoryItem("7832ebf3-e200-4a87-8cf5-b578a815b3e4")]
            public virtual Ranorex.ButtonTag BOOKNOW
            {
                get
                {
                    return _booknowInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BOOKNOW item info.
            /// </summary>
            [RepositoryItemInfo("7832ebf3-e200-4a87-8cf5-b578a815b3e4")]
            public virtual RepoItemInfo BOOKNOWInfo
            {
                get
                {
                    return _booknowInfo;
                }
            }

            /// <summary>
            /// The CheckAvailability item.
            /// </summary>
            [RepositoryItem("8ece57fd-5e54-4e67-8bed-b42cfe03b7d0")]
            public virtual Ranorex.SpanTag CheckAvailability
            {
                get
                {
                    return _checkavailabilityInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CheckAvailability item info.
            /// </summary>
            [RepositoryItemInfo("8ece57fd-5e54-4e67-8bed-b42cfe03b7d0")]
            public virtual RepoItemInfo CheckAvailabilityInfo
            {
                get
                {
                    return _checkavailabilityInfo;
                }
            }

            /// <summary>
            /// The LiTag3A item.
            /// </summary>
            [RepositoryItem("2900c749-c475-437c-8dde-47f6cd9eec66")]
            public virtual Ranorex.LiTag LiTag3A
            {
                get
                {
                    return _litag3aInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTag3A item info.
            /// </summary>
            [RepositoryItemInfo("2900c749-c475-437c-8dde-47f6cd9eec66")]
            public virtual RepoItemInfo LiTag3AInfo
            {
                get
                {
                    return _litag3aInfo;
                }
            }
        }

        /// <summary>
        /// The StateBankOfIndiaInternetBankingAppFolder folder.
        /// </summary>
        [RepositoryFolder("0e02063f-5773-4a5b-8698-a770b37dbca7")]
        public partial class StateBankOfIndiaInternetBankingAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clickhereInfo;

            /// <summary>
            /// Creates a new StateBankOfIndiaInternetBanking  folder.
            /// </summary>
            public StateBankOfIndiaInternetBankingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("StateBankOfIndiaInternetBanking", "/dom[@domain='merchant.onlinesbi.com']", parentFolder, 30000, null, false, "0e02063f-5773-4a5b-8698-a770b37dbca7", "")
            {
                _clickhereInfo = new RepoItemInfo(this, "ClickHere", ".//div[#'login_block']/div[5]/ul/?/?/a[@innertext='Click here']", 30000, null, "87025bf6-e093-4f76-b2b3-9903e64fa5d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0e02063f-5773-4a5b-8698-a770b37dbca7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0e02063f-5773-4a5b-8698-a770b37dbca7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClickHere item.
            /// </summary>
            [RepositoryItem("87025bf6-e093-4f76-b2b3-9903e64fa5d5")]
            public virtual Ranorex.ATag ClickHere
            {
                get
                {
                    return _clickhereInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ClickHere item info.
            /// </summary>
            [RepositoryItemInfo("87025bf6-e093-4f76-b2b3-9903e64fa5d5")]
            public virtual RepoItemInfo ClickHereInfo
            {
                get
                {
                    return _clickhereInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}