///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Goibibo_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Train1 recording.
    /// </summary>
    [TestModule("c52c410b-565b-472a-bc1d-21caa1f8893d", ModuleType.Recording, 1)]
    public partial class Train1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Train repository.
        /// </summary>
        public static Train repo = Train.Instance;

        static Train1 instance = new Train1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Train1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Train1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.IconTrainFrontViewDbBlueIco24Lh1' at 18;19.", repo.OnlineFlightBookingHotelsBusAmp.IconTrainFrontViewDbBlueIco24Lh1Info, new RecordItemIndex(0));
            repo.OnlineFlightBookingHotelsBusAmp.IconTrainFrontViewDbBlueIco24Lh1.Click("18;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GosuggestInputL' at 325;14.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(1));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.Click("325;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputL'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(2));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputL);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}delhi' with focus on 'OnlineFlightBookingHotelsBusAmp.GosuggestInputL'.", repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputLInfo, new RecordItemIndex(3));
            repo.OnlineFlightBookingHotelsBusAmp.GosuggestInputL.PressKeys("{Back}delhi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.MainTxt' at 200;4.", repo.OnlineFlightBookingHotelsBusAmp.MainTxtInfo, new RecordItemIndex(4));
            repo.OnlineFlightBookingHotelsBusAmp.MainTxt.Click("200;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL1' at 139;19.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL1Info, new RecordItemIndex(5));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL1.Click("139;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL1'.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL1Info, new RecordItemIndex(6));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL1);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}mumbai' with focus on 'OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL1'.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL1Info, new RecordItemIndex(7));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.GosuggestInputL1.PressKeys("{Back}mumbai");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.MainTxt' at 126;8.", repo.OnlineFlightBookingHotelsBusAmp.MainTxtInfo, new RecordItemIndex(8));
            repo.OnlineFlightBookingHotelsBusAmp.MainTxt.Click("126;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GiSearch.Text' at 100;10.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.TextInfo, new RecordItemIndex(9));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.Text.Click("100;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GiSearch.DayPickerNavButtonDayPickerNavButton' at 9;6.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.DayPickerNavButtonDayPickerNavButtonInfo, new RecordItemIndex(10));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.DayPickerNavButtonDayPickerNavButton.Click("9;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GiSearch.DivTag17' at 7;12.", repo.OnlineFlightBookingHotelsBusAmp.GiSearch.DivTag17Info, new RecordItemIndex(11));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearch.DivTag17.Click("7;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.GiSearchBtn' at 39;19.", repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtnInfo, new RecordItemIndex(12));
            repo.OnlineFlightBookingHotelsBusAmp.GiSearchBtn.Click("39;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(13));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.CheckAvailability' at 4;0.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.CheckAvailabilityInfo, new RecordItemIndex(14));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.CheckAvailability.Click("4;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(15));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(16));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.LiTag3A' at 26;6.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.LiTag3AInfo, new RecordItemIndex(17));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.LiTag3A.Click("26;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(18));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(19));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.BOOKNOW' at 54;11.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.BOOKNOWInfo, new RecordItemIndex(20));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.BOOKNOW.Click("54;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(21));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(22));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(23));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Male' on item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControlInputMedium'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControlInputMediumInfo, new RecordItemIndex(24));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FormControlInputMedium.Element.SetAttributeValue("TagValue", "Male");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(25));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 120 units.", new RecordItemIndex(26));
            Mouse.ScrollWheel(120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1' at 101;30.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1Info, new RecordItemIndex(27));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1.Click("101;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1Info, new RecordItemIndex(28));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}Devendra' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1Info, new RecordItemIndex(29));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1.PressKeys("{Back}Devendra");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(30));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number' at 56;19.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.NumberInfo, new RecordItemIndex(31));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number.Click("56;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}22' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.NumberInfo, new RecordItemIndex(32));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number.PressKeys("{Back}{Back}22");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number' at 59;13.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.NumberInfo, new RecordItemIndex(33));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number.Click("59;13");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.NumberInfo, new RecordItemIndex(34));
            //Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number);
            //Keyboard.Press(System.Windows.Forms.Keys.A, 30, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}22' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.NumberInfo, new RecordItemIndex(35));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number.PressKeys("{Back}22");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(36));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2' at 178;22.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2Info, new RecordItemIndex(37));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2.Click("178;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2Info, new RecordItemIndex(38));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2Info, new RecordItemIndex(39));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2.PressKeys("{Back}testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3' at 115;12.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3Info, new RecordItemIndex(40));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3.Click("115;12");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.NumberInfo, new RecordItemIndex(41));
            //Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number);
            //Keyboard.Press(System.Windows.Forms.Keys.A, 30, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1Info, new RecordItemIndex(42));
            //Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1);
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3Info, new RecordItemIndex(43));
            Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}9999999999' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3Info, new RecordItemIndex(44));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3.PressKeys("{Back}9999999999");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1' at 115;22.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1Info, new RecordItemIndex(45));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1.Click("115;22");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}Devendra' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1Info, new RecordItemIndex(46));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text1.PressKeys("{Back}Devendra");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number' at 65;17.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.NumberInfo, new RecordItemIndex(47));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number.Click("65;17");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}22' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.NumberInfo, new RecordItemIndex(48));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Number.PressKeys("{Back}22");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(49));
            //Mouse.ScrollWheel(-480);
            //Delay.Milliseconds(500);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2' at 179;15.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2Info, new RecordItemIndex(50));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2.Click("179;15");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}a{LControlKey up}{Back}testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2Info, new RecordItemIndex(51));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text2.PressKeys("{LControlKey down}a{LControlKey up}{Back}testnoc009{LShiftKey down}{@ down}{LShiftKey up}gmail.com");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3' at 108;9.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3Info, new RecordItemIndex(52));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3.Click("108;9");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3Info, new RecordItemIndex(53));
            //Keyboard.PrepareFocus(repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3);
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}9999999999' with focus on 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3'.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3Info, new RecordItemIndex(54));
            //repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Text3.PressKeys("{Back}9999999999");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Button' at 184;4.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.ButtonInfo, new RecordItemIndex(55));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Button.Click("184;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(56));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(57));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.SpanTagFareBreakup' at 2;10.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.SpanTagFareBreakupInfo, new RecordItemIndex(58));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.SpanTagFareBreakup.Click("2;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.FrIconCloseFont12LtPopClose' at 4;7.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FrIconCloseFont12LtPopCloseInfo, new RecordItemIndex(59));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.FrIconCloseFont12LtPopClose.Click("4;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.Button1' at 84;10.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Button1Info, new RecordItemIndex(60));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.Button1.Click("84;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.ButtonTagYes' at 34;13.", repo.OnlineFlightBookingHotelsBusAmp.ButtonTagYesInfo, new RecordItemIndex(61));
            repo.OnlineFlightBookingHotelsBusAmp.ButtonTagYes.Click("34;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(62));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.NetBanking' at 44;18.", repo.OnlineFlightBookingHotelsBusAmp.NetBankingInfo, new RecordItemIndex(63));
            repo.OnlineFlightBookingHotelsBusAmp.NetBanking.Click("44;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.PayNetbRb' at 4;3.", repo.OnlineFlightBookingHotelsBusAmp.PayNetbRbInfo, new RecordItemIndex(64));
            repo.OnlineFlightBookingHotelsBusAmp.PayNetbRb.Click("4;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.Submit' at 231;20.", repo.OnlineFlightBookingHotelsBusAmp.SubmitInfo, new RecordItemIndex(65));
            repo.OnlineFlightBookingHotelsBusAmp.Submit.Click("231;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(66));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StateBankOfIndiaInternetBanking.ClickHere' at 27;2.", repo.StateBankOfIndiaInternetBanking.ClickHereInfo, new RecordItemIndex(67));
            repo.StateBankOfIndiaInternetBanking.ClickHere.Click("27;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.SomeDivTag.BookAgain' at 77;21.", repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.BookAgainInfo, new RecordItemIndex(68));
            repo.OnlineFlightBookingHotelsBusAmp.SomeDivTag.BookAgain.Click("77;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma' at 61;10.", repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideImaInfo, new RecordItemIndex(69));
            repo.OnlineFlightBookingHotelsBusAmp.HttpsGoibiboIbcdnComStyleguideIma.Click("61;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
